<div class="min-w-0 space-y-5 text-rt-text dark:text-rt-dark-text" data-dropbox-settings>
    @if(!$ready)
        <p class="rounded-xl bg-rt-surface-muted p-4 text-sm dark:bg-rt-dark-surface-muted">Dropbox ist noch nicht eingerichtet. Die Datenbankerweiterung muss zuerst auf diesem Server installiert werden.</p>
    @else
        @php
            $fields = \App\Services\Dropbox\SyncLabels::FIELDS;
            $labels = ['connection' => 'Verbindung', 'sources' => 'Quellen & Vorlagen', 'identities' => 'Zuordnungen', 'data' => 'Fachdaten', 'conflicts' => 'Konflikte', 'activity' => 'Protokoll'];
        @endphp
        <div class="flex flex-wrap items-start justify-between gap-4 border-b border-rt-border/60 pb-4 dark:border-rt-dark-border/60">
            <div>
                <div class="flex flex-wrap items-center gap-2"><h3 class="text-lg font-semibold">Dropbox / Excel-Synchronisierung</h3><span class="rounded-full bg-rt-surface-muted px-3 py-1 text-xs font-semibold dark:bg-rt-dark-surface-muted">{{ $connection->mode->label() }}</span></div>
                <p class="mt-1 text-sm text-rt-muted dark:text-rt-dark-muted">{{ $connection->refresh_token ? $connection->account_label : 'Noch kein Dropbox-Konto verbunden' }}</p>
            </div>
            <div class="flex flex-wrap items-center gap-2 text-sm tabular-nums">
                <span>{{ $pending }} offen</span><span aria-hidden="true">·</span><span>{{ $conflicts->total() }} Konflikte</span>
                <x-ui.buttons.button-basic type="button" mode="secondary" wire:click="refreshStatus" wire:loading.attr="disabled">Aktualisieren</x-ui.buttons.button-basic>
                @if($connection->mode->active())<x-ui.buttons.button-basic type="button" mode="secondary" wire:click="stop" wire:loading.attr="disabled">Abgleich ausschalten</x-ui.buttons.button-basic>@endif
            </div>
        </div>
        @if($notice)<p role="status" class="rounded-xl bg-rt-accent-soft/40 px-4 py-3 text-sm dark:bg-rt-dark-accent-soft/30">{{ $notice }}</p>@endif
        @if($errors->any())<div role="alert" class="rounded-xl border-l-4 border-rt-accent bg-rt-accent-soft/40 p-4 text-sm dark:bg-rt-dark-accent-soft/30"><ul class="list-inside list-disc space-y-1">@foreach($errors->all() as $message)<li>{{ $message }}</li>@endforeach</ul></div>@endif
        @if($running)<p class="text-sm">{{ $running }} Verarbeitung(en) laufen noch. Ein bereits gestarteter Upload kann auch nach dem Ausschalten abgeschlossen werden.</p>@endif
        @if($connection->closing)<p role="status" class="rounded-xl bg-rt-surface-muted p-4 text-sm dark:bg-rt-dark-surface-muted">Abschlussabgleich läuft. Offene Änderungen und Konflikte klären; anschließend werden Archivkopien erstellt und Dropbox getrennt.</p>@endif
        <nav class="flex flex-wrap gap-2" aria-label="Dropbox-Einstellungsbereiche">
            @foreach($labels as $key => $label)<x-ui.buttons.button-basic type="button" :mode="$panel === $key ? 'primary' : 'secondary'" wire:click="$set('panel', '{{ $key }}')" :aria-current="$panel === $key ? 'page' : 'false'">{{ $label }}</x-ui.buttons.button-basic>@endforeach
        </nav>

        @if($panel === 'connection')
            <form wire:submit="save" class="space-y-5">
                <div class="grid min-w-0 gap-4 md:grid-cols-2">
                    <div><x-ui.forms.label for="dropbox-key" value="App-Key" /><x-ui.forms.input id="dropbox-key" wire:model="form.app_key" autocomplete="off" /></div>
                    <div><x-ui.forms.label for="dropbox-secret" value="App-Secret" /><x-ui.forms.input id="dropbox-secret" type="password" wire:model="form.app_secret" autocomplete="new-password" :placeholder="$connection->app_secret ? 'Gespeichert – leer lassen zum Beibehalten' : 'App-Secret eingeben'" /></div>
                </div>
                <div class="space-y-3 rounded-xl bg-rt-surface-muted p-4 dark:bg-rt-dark-surface-muted">
                    @foreach(['OAuth-Rücksprungadresse' => route('dropbox.callback'), 'Webhook-Adresse' => route('dropbox.webhook')] as $label => $url)
                        <div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between" x-data="{ copied: false }">
                            <div class="min-w-0"><p class="text-xs font-semibold text-rt-muted dark:text-rt-dark-muted">{{ $label }}</p><code class="break-all text-xs">{{ $url }}</code></div>
                            <x-ui.buttons.button-basic type="button" mode="secondary" :data-copy-url="$url" x-on:click="navigator.clipboard.writeText($el.dataset.copyUrl).then(() => copied = true).catch(() => copied = false)"><span x-text="copied ? 'Kopiert' : 'Kopieren'">Kopieren</span></x-ui.buttons.button-basic>
                        </div>
                    @endforeach
                    <p class="text-xs leading-5 text-rt-muted dark:text-rt-dark-muted">In der Dropbox App Console eine Anwendung mit Zugriff auf vorhandene Dateien einrichten. Die Anmeldung erfolgt bei Dropbox. Für Hintergrundabgleich und Rückübertragung werden Lese- und Schreibrechte benötigt.</p>
                </div>
                <div class="flex flex-wrap gap-2">
                    <x-ui.buttons.button-basic type="submit" mode="primary" wire:loading.attr="disabled">Einstellungen speichern</x-ui.buttons.button-basic>
                    <a href="{{ route('dropbox.connect') }}" class="inline-flex min-h-11 items-center rounded-xl border border-rt-border px-4 text-sm font-semibold hover:text-rt-accent focus-visible:outline focus-visible:outline-2 focus-visible:outline-rt-accent dark:border-rt-dark-border">Mit Dropbox verbinden</a>
                    <x-ui.buttons.button-basic type="button" mode="secondary" wire:click="testConnection" wire:loading.attr="disabled">Verbindung testen</x-ui.buttons.button-basic>
                    @if($connection->refresh_token)<x-ui.buttons.button-basic type="button" mode="secondary" wire:click="disconnect" wire:confirm="Dropbox trennen und ausstehende automatische Übernahmen beenden?" wire:loading.attr="disabled">Trennen</x-ui.buttons.button-basic>@endif
                </div>
                <p class="text-xs text-rt-muted dark:text-rt-dark-muted">Freigegebene Rechte: {{ implode(', ', $connection->scopes ?? []) ?: 'Noch keine' }}</p>
            </form>
            <section class="space-y-4 border-t border-rt-border/60 pt-5 dark:border-rt-dark-border/60">
                <h4 class="font-semibold">Betriebsart und Aktivierung</h4>
                <div class="grid gap-3 md:grid-cols-2">
                    @foreach(\App\Enums\DropboxMode::cases() as $option)
                        <label class="flex min-h-14 cursor-pointer items-start gap-3 rounded-xl bg-rt-surface-muted p-4 dark:bg-rt-dark-surface-muted">
                            <input type="radio" wire:model.live="mode" value="{{ $option->value }}" class="mt-1 h-5 w-5 text-rt-accent focus:ring-rt-accent" />
                            <span><span class="block text-sm font-semibold">{{ $option->label() }}</span><span class="mt-1 block text-xs leading-5 text-rt-muted dark:text-rt-dark-muted">{{ match($option->value) { 'off' => 'Automatische Verarbeitung aus; manuelle Vorschau möglich.', 'preview' => 'Beide Richtungen prüfen, ohne Änderungen zu übernehmen.', 'import' => 'Excel übernehmen; App-Änderungen für späteren Export erhalten.', 'bidirectional' => 'Excel und App gegenseitig abgleichen; Konflikte vorlegen.', default => 'Abschlussabgleich, Archivkopien und Verbindung beenden.' } }}</span></span>
                        </label>
                    @endforeach
                </div>
                @if($mode === 'app_only')<x-ui.forms.checkbox wire:model="desktopUploadsFinished" label="Alle Excel-Bearbeitungen sind gespeichert und hochgeladen. Während des Abschlusses wird Excel nicht weiter bearbeitet." />@endif
                <div class="flex flex-wrap gap-2"><x-ui.buttons.button-basic type="button" mode="secondary" wire:click="preview" wire:loading.attr="disabled">Vorschau starten</x-ui.buttons.button-basic><x-ui.buttons.button-basic type="button" mode="primary" wire:click="activate" wire:loading.attr="disabled">{{ $mode === 'app_only' ? 'Abschlussabgleich starten' : 'Betriebsart aktivieren' }}</x-ui.buttons.button-basic></div>
                <p class="text-sm text-rt-muted dark:text-rt-dark-muted">Gespeicherte App-Änderungen werden unmittelbar vorgemerkt. Entwürfe tragen in Excel <strong>[ENTWURF]</strong>; die Schichtplan-Veröffentlichung erfolgt weiterhin in der App.</p>
            </section>
        @elseif($panel === 'sources')
            <form wire:submit="save" class="space-y-5">
                <div class="grid min-w-0 gap-4 md:grid-cols-2">
                    <div><x-ui.forms.label for="dropbox-folders" value="Dispositionsordner (eine Dropbox-Adresse pro Zeile)" /><x-ui.forms.textarea id="dropbox-folders" wire:model="folders" rows="3" placeholder="/Disposition" /></div>
                    <div class="space-y-3"><div><x-ui.forms.label for="dropbox-matrix" value="Kompetenzmatrix (vollständiger Dropbox-Pfad)" /><x-ui.forms.input id="dropbox-matrix" wire:model="form.matrix_path" /></div><div><x-ui.forms.label for="dropbox-pattern" value="Dateinamensregel" /><x-ui.forms.input id="dropbox-pattern" wire:model="form.filename_rule" /></div></div>
                </div>
                <div class="grid gap-x-6 gap-y-1 md:grid-cols-2">
                    @foreach(['auto_discover' => 'Neue passende Wochen automatisch verwenden', 'watch_history' => 'Ältere Wochen weiterhin beobachten', 'create_workbooks' => 'Fehlende Wochenmappen aus Vorlage erstellen', 'create_sheets' => 'Fehlende Mitarbeiterblätter erstellen', 'append_rows' => 'Neue fachliche Zeilen ergänzen'] as $key => $label)<x-ui.forms.checkbox wire:model="form.{{ $key }}" :label="$label" />@endforeach
                </div>
                <div class="space-y-3"><p class="text-sm font-semibold">Weitere zugeordnete Quelldateien</p>@foreach($form['additional_sources'] ?? [] as $index => $configured)<div class="grid gap-2 sm:grid-cols-[1fr_180px_auto]" wire:key="extra-source-{{ $index }}"><x-ui.forms.input wire:model="form.additional_sources.{{ $index }}.path" aria-label="Vollständiger Dropbox-Dateipfad" placeholder="/Disposition/Datei.xlsx" /><x-ui.forms.select wire:model="form.additional_sources.{{ $index }}.profile" aria-label="Dateiprofil"><option value="weekly">Disposition</option><option value="matrix">Kompetenzmatrix</option></x-ui.forms.select><x-ui.buttons.button-basic type="button" mode="secondary" wire:click="removeSource({{ $index }})">Entfernen</x-ui.buttons.button-basic></div>@endforeach<x-ui.buttons.button-basic type="button" mode="secondary" wire:click="addSource">Datei hinzufügen</x-ui.buttons.button-basic></div>
                <fieldset><legend class="mb-2 text-sm font-semibold">Datenbereiche</legend><div class="grid gap-1 sm:grid-cols-2">@foreach(['planning' => 'Aufträge und Schichten', 'assignments' => 'Mitarbeiterzuordnungen', 'contacts' => 'Abbildbare Stammdaten', 'competencies' => 'Kompetenzen und gemeldete Nachweise'] as $key => $label)<x-ui.forms.checkbox wire:model="form.domains" :value="$key" :label="$label" />@endforeach</div></fieldset>
                <div class="grid gap-4 sm:grid-cols-3">
                    <div><x-ui.forms.label for="dropbox-debounce" value="Ereignisse bündeln" /><x-ui.forms.select id="dropbox-debounce" wire:model="form.debounce_seconds">@foreach([2,5,10] as $seconds)<option value="{{ $seconds }}">{{ $seconds }} Sekunden</option>@endforeach</x-ui.forms.select></div>
                    <div><x-ui.forms.label for="dropbox-check" value="Kontrollabfrage" /><x-ui.forms.select id="dropbox-check" wire:model="form.check_minutes">@foreach([5,15,60] as $minutes)<option value="{{ $minutes }}">{{ $minutes }} Minuten</option>@endforeach</x-ui.forms.select></div>
                    <div><x-ui.forms.label for="dropbox-zone" value="Zeitzone" /><x-ui.forms.input id="dropbox-zone" wire:model="form.timezone" readonly /></div>
                </div>
                <p class="text-xs leading-5 text-rt-muted dark:text-rt-dark-muted">Webhooks lösen den Abgleich nach dem Hochladen aus. Die Kontrollabfrage holt ausgebliebene Meldungen nach. „Erstmals erkannt“ bezeichnet die Aufnahme in RailTime, kein Dropbox-Erstellungsdatum.</p>
                <x-ui.buttons.button-basic type="submit" mode="primary" wire:loading.attr="disabled">Einstellungen speichern</x-ui.buttons.button-basic>
            </form>
            <section class="space-y-3 border-t border-rt-border/60 pt-5 dark:border-rt-dark-border/60">
                <h4 class="font-semibold">Bereinigte Vorlagen</h4>
                <div class="grid gap-3 sm:grid-cols-2">@foreach(['week_template' => 'Wochenmappe', 'employee_template' => 'Mitarbeiterblatt'] as $key => $label)<p class="text-sm"><strong>{{ $label }}:</strong> {{ $connection->option($key) ? 'Geprüfte Vorlage gespeichert' : 'Noch keine Vorlage' }}</p>@endforeach</div>
                <x-ui.forms.label for="dropbox-template" value="Vorlagendatei auswählen (.xlsx)" /><x-ui.forms.input id="dropbox-template" type="file" wire:model="templateUpload" accept=".xlsx" />
                <p class="text-xs text-rt-muted dark:text-rt-dark-muted">Aus der Datei werden Überschriften, Spaltenbreiten und Zellformate übernommen. Historische Daten, Bilder und Kommentare werden für neue Vorlagen entfernt; bestehende Arbeitsmappen bleiben erhalten.</p>
                <div class="flex flex-wrap gap-2"><x-ui.buttons.button-basic type="button" mode="secondary" wire:click="saveTemplate('week_template')" wire:loading.attr="disabled">Als Wochenvorlage prüfen und speichern</x-ui.buttons.button-basic><x-ui.buttons.button-basic type="button" mode="secondary" wire:click="saveTemplate('employee_template')" wire:loading.attr="disabled">Als Mitarbeiterblatt prüfen und speichern</x-ui.buttons.button-basic></div>
            </section>
            <section class="space-y-3"><h4 class="font-semibold">Erkannte Quellen</h4>
                @forelse($sources as $source)<div class="flex flex-wrap items-start justify-between gap-3 border-t border-rt-border/60 py-3 dark:border-rt-dark-border/60"><div class="min-w-0"><p class="break-all text-sm font-semibold">{{ $source->name }}</p><p class="break-all text-xs text-rt-muted dark:text-rt-dark-muted">{{ $source->path }}</p><p class="mt-1 text-xs">Einsatzwochen: {{ implode(', ', $source->weeks ?? []) ?: 'Noch zu prüfen' }}</p></div><div class="text-xs"><p>{{ match($source->state) { 'synchronized' => 'Synchronisiert', 'conflicts' => 'Konflikte prüfen', 'pending_export' => 'Rückübertragung offen', 'processing' => 'Abgleich läuft', 'preview' => 'Vorschau erstellt', 'missing' => 'Datei fehlt', 'excluded' => 'Nicht eingebunden', default => 'Neu erkannt' } }}</p><p class="mt-1 text-rt-muted dark:text-rt-dark-muted">Erstmals erkannt: {{ $source->first_seen_at->timezone('Europe/Berlin')->format('d.m.Y H:i') }}</p></div></div>@empty<p class="py-4 text-sm text-rt-muted dark:text-rt-dark-muted">Nach der Verbindung eine Vorschau starten. Passende Dateien erscheinen hier automatisch.</p>@endforelse
            </section>
        @elseif($panel === 'identities')
            <p class="text-sm text-rt-muted dark:text-rt-dark-muted">Excel-Bezeichnungen ausdrücklich einem Mitarbeiterkonto oder einem Dienstleister zuordnen. Es werden keine Anmeldekonten aus Excel angelegt.</p>
            <x-ui.forms.input wire:model.live.debounce.300ms="search" label="Person oder Dienstleister suchen" />
            <div class="divide-y divide-rt-border/60 dark:divide-rt-dark-border/60">
                @forelse($identities as $identity)<div wire:key="dropbox-identity-{{ $identity->id }}" class="grid items-end gap-3 py-4 lg:grid-cols-[1fr_180px_1fr_auto]"><div><p class="text-sm font-semibold">{{ $identity->details['display_name'] ?? $identity->alias }}</p><p class="text-xs text-rt-muted dark:text-rt-dark-muted">{{ $identity->kind === 'unresolved' ? 'Zuordnung offen' : 'Zuordnung gespeichert' }}</p></div><div><x-ui.forms.label :for="'identity-kind-'.$identity->id" value="Art" /><x-ui.forms.select :id="'identity-kind-'.$identity->id" wire:model="identityForms.{{ $identity->id }}.kind"><option value="unresolved">Noch offen</option><option value="employee">Mitarbeiter</option><option value="provider">Dienstleister</option></x-ui.forms.select></div><div><x-ui.forms.label :for="'identity-user-'.$identity->id" value="Mitarbeiterkonto" /><x-ui.forms.select :id="'identity-user-'.$identity->id" wire:model="identityForms.{{ $identity->id }}.user_id"><option value="">Kein Konto</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->name }}</option>@endforeach</x-ui.forms.select></div><x-ui.buttons.button-basic type="button" mode="secondary" wire:click="saveIdentity({{ $identity->id }})" wire:loading.attr="disabled">Zuordnung speichern</x-ui.buttons.button-basic></div>@empty<p class="py-4 text-sm">Noch keine Personen erkannt.</p>@endforelse
            </div>{{ $identities->links() }}
        @elseif($panel === 'conflicts')
            @if($selectedConflict)
                <section class="space-y-4 rounded-xl bg-rt-surface-muted p-4 dark:bg-rt-dark-surface-muted">
                    <div class="flex items-start justify-between gap-3"><h4 class="font-semibold">{{ \App\Services\Dropbox\SyncLabels::error($selectedConflict->reason) }}</h4><x-ui.buttons.button-basic type="button" mode="secondary" wire:click="closeConflict">Schließen</x-ui.buttons.button-basic></div>
                    @foreach($selectedConflict->snapshot['fields'] ?? [] as $field => $versions)
                        <div wire:key="conflict-field-{{ $field }}" class="space-y-3 border-t border-rt-border/60 pt-3 dark:border-rt-dark-border/60"><h5 class="text-sm font-semibold">{{ $fields[$field] ?? $field }}</h5><div class="grid gap-3 sm:grid-cols-3">@foreach(['Letzter gemeinsamer Stand' => $versions[0]['baseline'] ?? null, 'Excel' => $versions[0]['excel'] ?? ($versions[0]['values'][0] ?? null), 'App' => $selectedConflict->snapshot['app'][$field] ?? null] as $label => $value)<div class="min-w-0"><p class="text-xs text-rt-muted dark:text-rt-dark-muted">{{ $label }}</p><p class="break-words text-sm">{{ is_bool($value) ? ($value ? 'Ja' : 'Nein') : ($value ?? '—') }}</p></div>@endforeach</div><p class="text-xs text-rt-muted dark:text-rt-dark-muted">Herkunft: {{ $versions[0]['origin'] ?? 'Mehrere Excel-Vorkommen' }}</p><div class="grid gap-3 sm:grid-cols-2"><x-ui.forms.select :aria-label="'Entscheidung für '.($fields[$field] ?? $field)" wire:model="choices.{{ $field }}"><option value="app">App-Wert übernehmen</option><option value="excel">Excel-Wert übernehmen</option>@foreach($versions as $index => $version)@if($index > 0 && array_key_exists('excel', $version))<option value="excel.{{ $index }}">{{ $version['origin'] ?? 'Weiteres Excel-Vorkommen' }}: {{ $version['excel'] }}</option>@endif@endforeach<option value="custom">Eigenen Wert festlegen</option></x-ui.forms.select><x-ui.forms.input :aria-label="'Eigener Wert für '.($fields[$field] ?? $field)" wire:model="custom.{{ $field }}" /></div></div>
                    @endforeach
                    @if($selectedConflict->reason === 'field_conflict')
                        <div class="flex flex-wrap gap-2"><x-ui.buttons.button-basic type="button" mode="secondary" wire:click="reviewDecision">Entscheidung prüfen</x-ui.buttons.button-basic>@if($reviewedDecision)<x-ui.buttons.button-basic type="button" mode="primary" wire:click="applyDecision" wire:loading.attr="disabled">Entscheidung anwenden</x-ui.buttons.button-basic>@else<x-ui.buttons.button-basic type="button" mode="primary" disabled>Entscheidung anwenden</x-ui.buttons.button-basic>@endif</div>
                        @if($reviewedDecision)<dl class="grid gap-2 text-sm">@foreach($reviewedDecision as $field => $value)<div><dt class="inline font-semibold">{{ $fields[$field] ?? $field }}:</dt> <dd class="inline break-words">{{ is_bool($value) ? ($value ? 'Ja' : 'Nein') : ($value ?? '—') }}</dd></div>@endforeach</dl>@endif
                        <p class="text-xs text-rt-muted dark:text-rt-dark-muted">Die geprüfte Entscheidung wird erneut mit App und Dropbox verglichen. Veraltete Entscheidungen oder unzulässige Einsatzdaten werden nicht angewendet.</p>
                    @else
                        @if($selectedConflict->reason === 'not_representable')<p class="text-sm">Für diesen App-Datensatz fehlen Einsatzangaben oder eine passende Excel-Zuordnung. Es werden keine Daten erfunden. Er bleibt vollständig in der App erhalten.</p><x-ui.buttons.button-basic type="button" mode="secondary" wire:click="acknowledgeUnmapped">Als derzeit nur in App vorhanden vermerken</x-ui.buttons.button-basic>@endif
                        @if(in_array($selectedConflict->reason, ['mapping_required', 'ambiguous_row'], true))
                            <p class="text-sm">Excel-Zeile: {{ $selectedConflict->snapshot['sheet'] ?? '' }} · {{ $selectedConflict->snapshot['slot'] ?? '' }}</p>
                            <dl class="grid gap-2 text-sm sm:grid-cols-2">@foreach($selectedConflict->snapshot['values'] ?? [] as $key => $value)<div><dt class="font-semibold">{{ $fields[$key] ?? $key }}</dt><dd class="break-words">{{ is_bool($value) ? ($value ? 'Ja' : 'Nein') : ($value ?? '—') }}</dd></div>@endforeach</dl>
                            <label class="block text-sm">App-Datensatz suchen (Name oder Nummer)<input type="search" wire:model.live.debounce.300ms="mappingSearch" class="mt-1 w-full rounded-lg border-rt-border bg-rt-surface dark:border-rt-dark-border dark:bg-rt-dark-surface" /></label>
                            <x-ui.forms.select wire:model="targetRecord" aria-label="Zugehöriger App-Datensatz"><option value="">Vorhandenen App-Datensatz auswählen</option>@foreach($mappingRecords as $candidate)<option value="{{ $candidate->id }}">#{{ $candidate->id }} · {{ $candidate->metadata['employee_label'] ?? $candidate->metadata['subject'] ?? $candidate->model_type }} · {{ $candidate->metadata['name'] ?? $candidate->model_id }}</option>@endforeach</x-ui.forms.select>
                            <x-ui.buttons.button-basic type="button" mode="primary" wire:click="linkRow">Zeile diesem Datensatz zuordnen</x-ui.buttons.button-basic>
                        @endif
                        @if($selectedConflict->reason === 'row_missing')<p class="text-sm">Der App-Datensatz bleibt erhalten. Die fehlende Excel-Zeile kann aus dem aktuellen App-Stand wieder angelegt werden.</p><x-ui.buttons.button-basic type="button" mode="primary" wire:click="restoreRow">Fehlende Zeile wieder anlegen</x-ui.buttons.button-basic>@endif
                        @foreach($selectedConflict->snapshot['messages'] ?? [] as $messages)@foreach($messages as $message)<p class="text-sm">{{ $message }}</p>@endforeach@endforeach
                        @if($selectedConflict->reason === 'destination_required')<x-ui.forms.select wire:model="targetSource" aria-label="Zielmappe"><option value="">Zielmappe auswählen</option>@foreach($sources as $source)<option value="{{ $source->id }}">{{ $source->name }}</option>@endforeach</x-ui.forms.select><x-ui.buttons.button-basic type="button" mode="primary" wire:click="chooseDestination">Ziel festlegen</x-ui.buttons.button-basic>@endif
                        <x-ui.buttons.button-basic type="button" mode="secondary" wire:click="retryConflict({{ $selectedConflict->id }})">Nach Korrektur erneut prüfen</x-ui.buttons.button-basic>
                    @endif
                </section>
            @endif
            @forelse($conflicts as $conflict)<div class="flex flex-wrap items-center justify-between gap-3 border-t border-rt-border/60 py-3 dark:border-rt-dark-border/60" wire:key="dropbox-conflict-{{ $conflict->id }}"><div class="min-w-0"><p class="text-sm font-semibold">{{ \App\Services\Dropbox\SyncLabels::error($conflict->reason) }}</p><p class="text-xs text-rt-muted dark:text-rt-dark-muted">{{ $conflict->snapshot['sheet'] ?? '' }} {{ isset($conflict->snapshot['slot']) ? '· '.$conflict->snapshot['slot'] : '' }} · {{ $conflict->updated_at->timezone('Europe/Berlin')->format('d.m.Y H:i') }}</p></div><x-ui.buttons.button-basic type="button" mode="secondary" wire:click="selectConflict({{ $conflict->id }})">Prüfen</x-ui.buttons.button-basic></div>@empty<p class="py-4 text-sm">Keine offenen Konflikte.</p>@endforelse
            {{ $conflicts->links() }}
        @elseif($panel === 'data')
            <p class="text-sm text-rt-muted dark:text-rt-dark-muted">Abgebildete Fachdaten bearbeiten. Kompetenzangaben aus Excel bleiben von geprüften Nachweisen getrennt; gemeldete Istzeiten werden nicht automatisch freigegeben.</p>
            @if($recordId)
                @if(array_key_exists('color', $recordForm))
                    <div class="space-y-3 rounded-xl bg-rt-surface-muted p-4 dark:bg-rt-dark-surface-muted"><h4 class="font-semibold">Geprüften App-Nachweis zuordnen</h4><p class="text-sm">Änderungen dieses Nachweises werden in die ausgewählte Excel-Angabe übertragen. Eingehende Excel-Werte bleiben gemeldete Angaben und können einen Nachweis nicht freigeben.</p><div class="grid gap-3 sm:grid-cols-2"><x-ui.forms.select wire:model="qualificationType" aria-label="Nachweisart"><option value="">Keine Nachweiszuordnung</option>@foreach($qualificationTypes as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</x-ui.forms.select><x-ui.forms.select wire:model="qualificationField" aria-label="Nachweisangabe"><option value="valid_until">Gültig bis</option><option value="valid_from">Gültig ab</option><option value="status">Prüfstatus</option></x-ui.forms.select></div><x-ui.buttons.button-basic type="button" mode="secondary" wire:click="bindQualification">Nachweiszuordnung speichern</x-ui.buttons.button-basic></div>
                @endif
                <form wire:submit="saveRecord" class="space-y-4 rounded-xl bg-rt-surface-muted p-4 dark:bg-rt-dark-surface-muted"><h4 class="font-semibold">Datensatz bearbeiten</h4><div class="grid gap-4 md:grid-cols-2">
                    @foreach($recordForm as $field => $value)<div wire:key="record-field-{{ $field }}">@if(is_bool($value))<x-ui.forms.checkbox wire:model="recordForm.{{ $field }}" :label="$fields[$field] ?? $field" :disabled="$field === 'draft'" />@else<x-ui.forms.label :for="'dropbox-record-'.$field" :value="$fields[$field] ?? $field" /><x-ui.forms.input :id="'dropbox-record-'.$field" wire:model="recordForm.{{ $field }}" :type="in_array($field, ['starts','ends','actual_end']) ? 'time' : (in_array($field, ['date','birth_date']) ? 'date' : 'text')" />@endif</div>@endforeach
                </div><div class="flex flex-wrap gap-2"><x-ui.buttons.button-basic type="submit" mode="primary" wire:loading.attr="disabled">Speichern und Übertragung vormerken</x-ui.buttons.button-basic><x-ui.buttons.button-basic type="button" mode="secondary" wire:click="closeRecord">Abbrechen</x-ui.buttons.button-basic></div></form>
            @endif
            @foreach($records as $record)<div class="flex flex-wrap items-center justify-between gap-3 border-t border-rt-border/60 py-3 dark:border-rt-dark-border/60" wire:key="dropbox-record-{{ $record->id }}"><div><p class="text-sm font-semibold">{{ match($record->domain) { 'planning' => 'Einsatz', 'contacts' => 'Kontakt', default => 'Kompetenzangabe' } }} #{{ $record->model_id }}</p><p class="text-xs text-rt-muted dark:text-rt-dark-muted">{{ $record->metadata['subject'] ?? $record->metadata['employee_label'] ?? '' }} {{ $record->metadata['name'] ?? '' }}</p></div><x-ui.buttons.button-basic type="button" mode="secondary" wire:click="editRecord({{ $record->id }})">Bearbeiten</x-ui.buttons.button-basic></div>@endforeach
            {{ $records->links() }}
            <details class="border-t border-rt-border/60 pt-4 dark:border-rt-dark-border/60"><summary class="cursor-pointer text-sm font-semibold">Neue Kompetenzangabe</summary><form wire:submit="createFact" class="mt-4 grid gap-4 md:grid-cols-2"><div><x-ui.forms.label for="fact-person" value="Person" /><x-ui.forms.select id="fact-person" wire:model="newFact.identity_id"><option value="">Person auswählen</option>@foreach($allIdentities as $identity)<option value="{{ $identity->id }}">{{ $identity->details['display_name'] ?? $identity->alias }}</option>@endforeach</x-ui.forms.select></div><div><x-ui.forms.label for="fact-kind" value="Bereich" /><x-ui.forms.select id="fact-kind" wire:model="newFact.kind"><option value="local_knowledge">Ortskunde</option><option value="introduction">Einweisung</option><option value="document">Unterlagen</option><option value="customer_authorization">Kundenfreigabe / Sperre</option></x-ui.forms.select></div>@foreach(['name' => 'Bezeichnung wie in Excel', 'scope' => 'Kunde / Ort / Oberbegriff', 'value' => 'Gemeldeter Wert', 'color' => 'Zellfarbe (ARGB, optional)'] as $key => $label)<div><x-ui.forms.label :for="'new-fact-'.$key" :value="$label" /><x-ui.forms.input :id="'new-fact-'.$key" wire:model="newFact.{{ $key }}" /></div>@endforeach<div><x-ui.buttons.button-basic type="submit" mode="primary">Kompetenzangabe speichern</x-ui.buttons.button-basic></div></form></details>
            <details class="border-t border-rt-border/60 pt-4 dark:border-rt-dark-border/60"><summary class="cursor-pointer text-sm font-semibold">Neuer Kontakt / Dienstleister</summary><form wire:submit="createContact" class="mt-4 grid gap-4 md:grid-cols-2">@foreach(['name' => 'Name in Excel', 'first_name' => 'Vorname', 'last_name' => 'Nachname', 'contact_email' => 'Kontakt-E-Mail', 'phone' => 'Telefon'] as $key => $label)<div><x-ui.forms.label :for="'new-contact-'.$key" :value="$label" /><x-ui.forms.input :id="'new-contact-'.$key" wire:model="newContact.{{ $key }}" /></div>@endforeach<div><x-ui.forms.label for="contact-kind" value="Art" /><x-ui.forms.select id="contact-kind" wire:model="newContact.kind"><option value="provider">Dienstleister</option><option value="unresolved">Mitarbeiter (Konto noch zuordnen)</option></x-ui.forms.select></div><div><x-ui.buttons.button-basic type="submit" mode="primary">Kontakt speichern</x-ui.buttons.button-basic></div></form></details>
        @else
            <section class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                @foreach(['Webhook-Eingang' => $connection->webhook_at, 'Excel → App' => $connection->imported_at, 'App → Excel' => $connection->exported_at] as $label => $date)<div><p class="text-xs text-rt-muted dark:text-rt-dark-muted">{{ $label }}</p><p class="mt-1 text-sm font-semibold tabular-nums">{{ $date?->timezone('Europe/Berlin')->format('d.m.Y H:i:s') ?? 'Noch kein erfolgreicher Lauf' }}</p></div>@endforeach
            </section>
            <section class="space-y-3 rounded-xl bg-rt-surface-muted p-4 dark:bg-rt-dark-surface-muted"><h4 class="font-semibold">Hintergrundverarbeitung</h4><p class="text-sm">Redis: {{ $health['redis'] ? 'Erreichbar' : 'Nicht erreichbar' }}</p>@foreach($health['workers'] as $queue => $ok)<p class="text-sm">{{ match($queue) { 'dropbox-events' => 'Dateiänderungen', 'dropbox-import' => 'Excel-Abgleich', default => 'App-Rückübertragung' } }}: {{ $ok ? 'Worker antwortet' : 'Kein aktueller Worker-Nachweis' }}</p>@endforeach<x-ui.buttons.button-basic type="button" mode="secondary" wire:click="testWorkers" wire:loading.attr="disabled">Hintergrundverarbeitung testen</x-ui.buttons.button-basic><p class="text-xs text-rt-muted dark:text-rt-dark-muted">Bei einer Unterbrechung bleiben angenommene Aufträge gespeichert. Der Server nimmt sie nach dem Wiederanlauf erneut auf.</p></section>
            <section class="space-y-3"><h4 class="font-semibold">Ausstehende Übertragungen</h4>@forelse($jobs as $job)<p class="border-t border-rt-border/60 py-2 text-sm dark:border-rt-dark-border/60">{{ \App\Services\Dropbox\SyncLabels::error($job->error_code) }} <span class="text-xs text-rt-muted dark:text-rt-dark-muted">· {{ $job->updated_at->timezone('Europe/Berlin')->format('d.m.Y H:i') }}</span></p>@empty<p class="text-sm text-rt-muted dark:text-rt-dark-muted">Keine ausstehenden Arbeitsaufträge.</p>@endforelse</section>
            <section class="space-y-3">
                <h4 class="font-semibold">Letzte Ergebnisse</h4>
                @forelse($runs as $run)
                    @php($summary = json_decode($run->summary ?? '{}', true))
                    <div class="flex flex-wrap justify-between gap-2 border-t border-rt-border/60 py-2 text-sm dark:border-rt-dark-border/60">
                        <span>{{ ($summary['preview'] ?? false) || $run->kind === 'preview' ? 'Vorschau' : ($run->kind === 'export' ? 'Rückübertragung' : 'Abgleich') }} · {{ $run->status === 'ok' ? 'Erfolgreich' : ($run->status === 'pending' ? 'Vorgemerkt' : 'Aufmerksamkeit erforderlich') }}@if(isset($summary['code'])) — {{ \App\Services\Dropbox\SyncLabels::error($summary['code']) }}@endif</span>
                        <span class="text-xs text-rt-muted dark:text-rt-dark-muted">{{ \Carbon\Carbon::parse($run->created_at)->timezone('Europe/Berlin')->format('d.m.Y H:i') }}</span>
                        @if(isset($summary['rows']))<p class="w-full text-xs">{{ $summary['rows'] }} Zeilen · {{ $summary['imported'] ?? 0 }} Übernahmen · {{ $summary['exported'] ?? 0 }} Rückübertragungen · {{ $summary['outgoing'] ?? 0 }} vorgesehene Rückübertragungen · {{ $summary['conflicts'] ?? 0 }} Konflikte</p>@endif
                        @if(isset($summary['preview_values']))
                            <details class="w-full"><summary class="cursor-pointer">Vorgesehene App-Werte · #{{ $summary['record_id'] }}</summary><p class="mt-2 text-xs text-rt-muted dark:text-rt-dark-muted">Vorschau ohne Übernahme. Der nächste Abgleich prüft Excel und App erneut.</p>
                                <dl class="mt-2 grid gap-2 sm:grid-cols-2">@foreach($summary['preview_values'] as $field => $value)<div><dt class="text-xs font-semibold">{{ $fields[$field] ?? $field }}</dt><dd class="break-words">{{ is_bool($value) ? ($value ? 'Ja' : 'Nein') : ($value ?? '—') }}</dd></div>@endforeach</dl>
                            </details>
                        @endif
                    </div>
                @empty<p class="text-sm text-rt-muted dark:text-rt-dark-muted">Noch keine Verarbeitung protokolliert.</p>@endforelse
            </section>
        @endif
        <p wire:loading role="status" class="text-sm text-rt-muted dark:text-rt-dark-muted">Wird verarbeitet …</p>
    @endif
</div>
