<section class="mt-4 space-y-4 rounded-2xl border border-rt-border bg-white p-4 dark:bg-rt-dark-surface">
    <div class="flex flex-wrap items-center justify-between gap-3"><h2 class="font-semibold">Arbeitsplätze & Client-Hilfe</h2><button type="button" wire:click="$set('showProvision', true)" class="min-h-10 rounded-xl border px-3 text-sm">Mitarbeiterbereitstellung</button></div>
    @if($notice)<p role="status" class="text-sm">{{ $notice }}</p>@endif
    <details><summary class="cursor-pointer text-sm font-semibold">Bestätigter Programmumfang je Arbeitsplatzprofil</summary>
        <form wire:submit="savePrograms" class="mt-3 space-y-3 text-sm">
            <label class="block">Profil<select wire:model="programProfile" wire:change="loadPrograms" class="mt-1 w-full rounded-xl border-rt-border"><option value="byod_managed">Privatgerät – verwaltet</option><option value="corporate_standard">Firmenarbeitsplatz</option></select></label>
            <button type="button" wire:click="loadPrograms" class="min-h-10 rounded-xl border px-3">Gespeicherte Pakete laden</button>
            <label class="block">Eine feste Paket-ID@Version pro Zeile<textarea wire:model="programLines" rows="5" class="mt-1 w-full rounded-xl border-rt-border" placeholder="Vendor.Application@1.2.3"></textarea></label>
            <p>Leere Liste erlaubt keine Desktop-Programminstallation. Jede Änderung widerruft die bisherige Umfangsfreigabe der betroffenen Geräte. Programme werden nicht gekauft, automatisch ausgeführt oder deinstalliert. Systemdienst-Aufträge benötigen weiterhin den gesonderten OpenUEM-Weg.</p>
            <button class="min-h-10 rounded-xl border px-3" wire:confirm="Programmumfang ändern und erneute Mitarbeiterzustimmung erforderlich machen?">Programmumfang speichern</button>
        </form>
    </details>
    @if($errors->any())<ul role="alert" class="text-sm text-red-700">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul>@endif
    <details><summary class="cursor-pointer text-sm font-semibold">Supportkontakt & Diagnoseaufbewahrung</summary><form wire:submit="saveSupport" class="mt-3 grid gap-3 sm:grid-cols-2"><label class="text-sm">Öffentliche IT-E-Mail<input wire:model="supportEmail" type="email" class="mt-1 w-full rounded-xl border-rt-border"></label><label class="text-sm">IT-Telefon<input wire:model="supportPhone" class="mt-1 w-full rounded-xl border-rt-border"></label><label class="text-sm">Aufbewahrung neuer Diagnosen (Tage)<input wire:model="retentionDays" type="number" min="1" max="90" class="mt-1 w-full rounded-xl border-rt-border"></label><button class="min-h-10 rounded-xl border px-3">Supporteinstellungen speichern</button><p class="text-xs text-rt-muted sm:col-span-2">Kontakt wird vor Anmeldung im Client angezeigt. Keine Geheimnisse eintragen. Standard 30 Tage; Ablaufentfernung benötigt den Laravel-Scheduler.</p></form></details>
    <details><summary class="cursor-pointer text-sm font-semibold">Microsoft-Bereitstellung – getrennter Schreibzugang</summary><form wire:submit="saveWriter" class="mt-3 space-y-3">
        <p class="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950">Vor App-Registrierung, Rechten oder Adminzustimmung in Microsoft Admin/Entra nachfragen. Dieser Bereich ersetzt nicht diese Zustimmung. Keine automatischen Lizenzkäufe; keine Geräte- oder Mail-Schreibrechte.</p>
        <p class="text-xs">Vorgesehene Anwendungsrechte: User.Create, User.Read.All, LicenseAssignment.Read.All, LicenseAssignment.ReadWrite.All, Domain.Read.All.</p>
        <label class="block text-sm">Tenant-ID<input wire:model="tenantId" class="mt-1 w-full rounded-xl border-rt-border"></label><label class="block text-sm">Client-ID der separaten Schreibanwendung<input wire:model="clientId" class="mt-1 w-full rounded-xl border-rt-border"></label><label class="block text-sm">Client-Geheimnis (Wert)<input type="password" autocomplete="new-password" wire:model="clientSecret" class="mt-1 w-full rounded-xl border-rt-border" placeholder="{{ $secretConfigured ? 'Gespeichert – leer lassen zum Beibehalten' : 'Noch nicht gespeichert' }}"></label>
        <label class="flex gap-2 text-sm"><input type="checkbox" wire:model="tenantApproval">Die konkrete Einrichtung und Rechtevergabe wurde im Mandanten ausdrücklich genehmigt.</label><label class="flex gap-2 text-sm"><input type="checkbox" wire:model="writerEnabled">Ausdrücklich freigegebene Mitarbeiteraufträge dürfen Microsoft-Konten und vorhandene Lizenzen zuweisen.</label><button class="min-h-10 rounded-xl border px-3">Schreibzugang speichern</button>
    </form></details>
    <x-dialog-modal wire:model="showProvision" maxWidth="4xl"><x-slot:title>Mitarbeiterbereitstellung</x-slot:title><x-slot:content>
        <div class="space-y-4"><p class="text-sm">Mitarbeiter bleiben bis zur Freigabe und verifizierten Microsoft-Anmeldung inaktiv. Ohne Office-Profil ist keine Office-Lizenz Pflicht. Zusätzliche Geräte verwenden denselben Auftrag.</p>
        <form wire:submit="approve" class="grid gap-3 text-sm sm:grid-cols-2"><label>Mitarbeiter<select wire:model="employeeId" class="w-full rounded-xl border-rt-border"><option value="">Inaktiven Mitarbeiter wählen</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->name }} · {{ $employee->email }}</option>@endforeach</select></label><label>Bestätigte Microsoft-Adresse<input wire:model="principal" type="email" class="w-full rounded-xl border-rt-border"></label><label>Nutzungsland (ISO, z. B. DE)<input wire:model="usageLocation" maxlength="2" class="w-full rounded-xl border-rt-border"></label><label>Arbeitsplatzprofil<select wire:model="profileKey" class="w-full rounded-xl border-rt-border">@foreach(\App\Services\DeviceManagement\WorkplaceProfileCatalog::all() as $key => $profile)<option value="{{ $key }}">{{ $profile['label'] }}</option>@endforeach</select></label><label class="sm:col-span-2">Vorhandene SKU-ID (leer ohne Office)<input wire:model="skuId" class="w-full rounded-xl border-rt-border"></label><label class="flex gap-2 sm:col-span-2"><input type="checkbox" wire:model="employeeConfirmed">Adresse, Nutzungsland, Profil und vorhandene Lizenz ausdrücklich bestätigen.</label><button class="min-h-10 rounded-xl border px-3">Auftrag freigeben</button></form>
        <label class="flex gap-2 rounded-xl border border-amber-200 p-3 text-sm"><input type="checkbox" wire:model="executeConfirmed">Die Microsoft-Änderung für den anschließend ausgewählten Auftrag ist ausdrücklich freigegeben. Nur vorhandene Lizenzplätze verwenden.</label>
        <div class="space-y-3">@foreach($orders as $order)<article class="rounded-xl border p-3 text-sm"><p class="font-semibold">{{ $order->user->name }} · {{ $order->principal }}</p><p>Konto: {{ $order->account_state }} · Lizenz: {{ $order->license_state }} · Exchange-Dienst: {{ $order->mailbox_state }} · Anmeldung: {{ $order->signed_in_at ? 'verifiziert' : 'ausstehend' }}</p><p>{{ $order->state }} {{ $order->error_code }}</p><p class="text-xs text-rt-muted">Ein provisionierter Exchange-Dienst ist noch kein erfolgreich getestetes Postfach. Unklare Ergebnisse werden abgeglichen, nicht blind wiederholt.</p>@if(!$order->signed_in_at && $order->state !== 'cancelled')<button type="button" wire:click="runProvision({{ $order->id }})" wire:loading.attr="disabled" class="mt-2 min-h-10 rounded-xl border px-3">Diesen Auftrag ausführen / abgleichen</button>@endif</article>@endforeach</div></div>
        @foreach($orders as $passwordOrder)
            @if(!$passwordOrder->signed_in_at && $passwordOrder->state !== 'cancelled')
                <button type="button" wire:click="cancelProvision({{ $passwordOrder->id }})" wire:confirm="Lokale Freigabe zurücknehmen? Microsoft-Konto und Lizenz bleiben unverändert." class="mt-3 min-h-10 rounded-xl border px-3 text-sm">Freigabe für {{ $passwordOrder->user->name }} zurücknehmen</button>
            @endif
            @if($passwordOrder->getRawOriginal('initial_password') && $passwordOrder->password_expires_at?->isFuture() && $passwordOrder->account_state === 'ready')
                <form method="POST" action="{{ route('devices.provision.password', $passwordOrder->id) }}" class="mt-3 rounded-xl border border-amber-200 p-3 text-sm">@csrf<p>{{ $passwordOrder->user->name }}: Startkennwort nur einmal abrufbar, maximal 24 Stunden gespeichert. Ausschließlich persönlich an den Mitarbeiter übergeben; nicht per E-Mail oder Ticket.</p><button class="mt-2 min-h-10 rounded-xl border px-3">Startkennwort einmalig sicher herunterladen</button></form>
            @endif
        @endforeach
    </x-slot:content><x-slot:footer><button type="button" wire:click="$set('showProvision', false)" class="min-h-10 rounded-xl border px-3">Schließen</button></x-slot:footer></x-dialog-modal>
</section>
