<section class="ops-stack min-w-0" data-ai-intake-inbox wire:poll.visible.10s>
    <div class="ops-toolbar"><div><h2 class="font-semibold">AI-Annahme</h2><p class="ops-muted">Eingänge, Rückfragen und Planungsvorschläge gemeinsam prüfen.</p></div>@if($ready)<x-ui.buttons.button-basic type="button" mode="primary" wire:click="openCapture"><i class="far fa-plus" aria-hidden="true"></i>Eingang erfassen</x-ui.buttons.button-basic>@endif</div>
    <x-operations.feedback />
    @if(!$ready)
        <p class="ops-muted">Die AI-Annahme ist noch nicht eingerichtet. Der Superadmin richtet die Datenbankerweiterung und das Dispositionspostfach ein.</p>
    @else
        @if(!$enabled)<p class="ops-muted" role="status">Die automatische Verarbeitung ist deaktiviert. Eingänge bleiben zur späteren Auswertung erhalten.</p>@endif
        <x-tables.toolbar title="AI-Eingänge filtern" id="ai-intake-filters" :search-in-header="true">
            <x-slot:search><x-tables.search-field context="page" wire:model.live.debounce.300ms="search" placeholder="AI-Eingang suchen" /></x-slot:search>
            <x-tables.filter-field label="Bearbeitung" for="ai-intake-status"><x-ui.forms.select id="ai-intake-status" wire:model.live="statusFilter"><option value="all">Alle Zustände</option>@foreach($labels as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</x-ui.forms.select></x-tables.filter-field>
        </x-tables.toolbar>
        <x-tables.table :columns="[['label'=>'Eingang','key'=>'title','width'=>'minmax(0,1.7fr)'],['label'=>'Kunde','key'=>'customer','width'=>'minmax(0,1fr)'],['label'=>'Bearbeitung','key'=>'status','width'=>'minmax(0,.8fr)'],['label'=>'Erfasst','key'=>'created','width'=>'minmax(0,.8fr)']]" :items="$intakes" table-key="ai-intake" detail-action="select" row-view="components.tables.rows.operations.ai-intake-row" empty="Noch keine AI-Eingänge für diese Auswahl." :flush-top="true" />
        {{ $intakes->links() }}
    @endif
    <x-operations.modal wire:model.live="captureOpen" title="Eingang erfassen" max-width="3xl">
        <form wire:submit="submit" class="ops-stack" x-data="aiIntakeRecorder($wire)" x-effect="if (!$wire.captureOpen) cancel()" x-on:ai-intake-submitted.window="fileName = ''">
            <x-operations.feedback :show-offline="false" />
            <div class="ops-form"><x-operations.field label="Anfrage / Gesprächsnotiz" model="text" type="textarea" maxlength="20000" :wide="true" /><x-operations.field label="Kontakt-E-Mail (optional)" model="contactEmail" type="email" :wide="true" /></div>
            <div><x-ui.forms.label for="ai-intake-files" value="Bilder, PDF, Excel/CSV, Text oder Audio" /><input id="ai-intake-files" type="file" multiple wire:model="uploads" accept=".jpg,.jpeg,.png,.webp,.pdf,.xlsx,.csv,.txt,.mp3,.wav,.m4a,.aac,.ogg,.flac,.webm" class="mt-2 block max-w-full text-sm" /><x-ui.forms.input-error for="uploads" /><x-ui.forms.input-error for="uploads.*" />
                @foreach($uploads as $file)<p class="mt-1 ops-muted">{{ $file->getClientOriginalName() }}</p>@endforeach
                <p class="mt-2 ops-muted">Bis zu {{ $limits['max_attachment_count'] }} Anlagen, insgesamt {{ number_format($limits['max_total_kilobytes']/1024,1,',','.') }} MB. Audio bis zu {{ number_format($limits['max_audio_kilobytes']/1024,1,',','.') }} MB.</p>
            </div>
            <section class="border-t border-rt-border pt-3 dark:border-rt-dark-border" aria-label="Sprachanfrage aufnehmen">
                <div class="ops-actions"><x-ui.buttons.button-basic type="button" x-on:click="start()" x-bind:disabled="recording || requesting || uploading"><i class="far fa-microphone" aria-hidden="true"></i>Sprachaufnahme starten</x-ui.buttons.button-basic><x-ui.buttons.button-basic type="button" x-on:click="stop()" x-bind:disabled="!recording">Beenden</x-ui.buttons.button-basic><x-ui.buttons.button-basic type="button" x-on:click="cancel()" x-bind:disabled="!recording && !requesting && !uploading">Verwerfen</x-ui.buttons.button-basic></div>
                <p class="mt-2 ops-muted" role="status" aria-live="polite"><span x-show="requesting">Mikrofonfreigabe ausstehend …</span><span x-show="recording" x-cloak>Aufnahme läuft · <span x-text="seconds"></span> Sekunden</span><span x-show="uploading" x-cloak>Aufnahme wird hochgeladen …</span><span x-text="fileName"></span></p><p x-show="error" x-text="error" role="alert" class="text-sm text-rt-red"></p><x-ui.forms.input-error for="audioUpload" />
                @if($audioUpload)<div class="ops-actions"><p class="ops-muted">Sprachaufnahme hinzugefügt.</p><x-ui.buttons.button-basic type="button" wire:click="removeAudio">Aufnahme entfernen</x-ui.buttons.button-basic></div>@endif
            </section>
            <div class="ops-actions"><x-ui.buttons.button-basic type="submit" mode="primary" wire:loading.attr="disabled" wire:target="submit,uploads,audioUpload" x-bind:disabled="recording || requesting || uploading">Eingang speichern</x-ui.buttons.button-basic><span wire:loading wire:target="submit" class="ops-muted" role="status">Eingang wird gespeichert …</span></div>
        </form>
    </x-operations.modal>
    <x-operations.modal wire:model.live="detailOpen" title="AI-Eingang prüfen" max-width="4xl" variant="drawer">
        @if($selected)
            <x-operations.feedback :show-offline="false" />
            <header><div class="ops-actions"><x-operations.status :value="$selected->status" :label="$labels[$selected->status] ?? 'Prüfung nötig'" /><span class="ops-muted">AI-{{ str_pad((string)$selected->id,6,'0',STR_PAD_LEFT) }}</span></div><h2 class="mt-2 text-lg font-semibold break-words">{{ $selected->title }}</h2><p class="mt-2 ops-muted break-words">{{ $selected->summary }}</p></header>
            @if($selected->revision !== $selectedRevision)<div class="ops-actions" role="status"><p class="ops-muted">Dieser Eingang wurde inzwischen ergänzt. Vor einer Änderung den aktuellen Stand laden.</p><x-ui.buttons.button-basic type="button" wire:click="select({{ $selected->id }})">Aktualisieren</x-ui.buttons.button-basic></div>@endif
            <div class="ops-actions"><x-ui.buttons.button-basic type="button" wire:click="reanalyze" wire:loading.attr="disabled" :disabled="!$enabled">Erneut analysieren</x-ui.buttons.button-basic><x-ui.buttons.button-basic type="button" wire:click="pause" wire:loading.attr="disabled">Pausieren</x-ui.buttons.button-basic>@if($selected->proposals->isNotEmpty() && empty($selected->inquiry_ids))<x-ui.buttons.button-basic type="button" wire:click="createInquiries" wire:loading.attr="disabled">Anfragen übernehmen</x-ui.buttons.button-basic>@endif</div>
            <x-ui.forms.input-error for="intake" />
            @if($selected->error_code)<p class="ops-muted" role="alert">Die Verarbeitung benötigt eine Prüfung. Quellen und erkannte Angaben bleiben erhalten.</p>@endif
            @if($selected->missing_fields)<section class="border-t border-rt-border pt-3 dark:border-rt-dark-border"><h3 class="font-semibold">Offene Angaben</h3><ul class="mt-2 list-disc pl-5 text-sm">@foreach($selected->missing_fields as $field)@php($fieldKey = is_array($field) ? ($field['field'] ?? '') : $field)<li>{{ is_array($field) && isset($field['question']) ? $field['question'] : ($fieldLabels[$fieldKey] ?? 'Angabe prüfen') }}</li>@endforeach</ul></section>@endif
            <section class="border-t border-rt-border pt-3 dark:border-rt-dark-border"><h3 class="font-semibold">Kundenzuordnung</h3><form wire:submit="assignCustomer" class="ops-form mt-3">
                <div class="ops-full"><x-ui.forms.label for="ai-intake-customer" value="Kunde" /><x-ui.forms.select id="ai-intake-customer" wire:model.live="assignCustomerId"><option value="">Bitte prüfen und zuordnen</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->company_name }}</option>@endforeach</x-ui.forms.select><x-ui.forms.input-error for="assignCustomerId" /></div>
                <div class="ops-full"><x-ui.forms.label for="ai-intake-contact" value="Kontakt" /><x-ui.forms.select id="ai-intake-contact" wire:model="assignContactId"><option value="">Hauptkontakt des Kunden</option>@foreach($contacts as $contact)<option value="{{ $contact->id }}">{{ $contact->name }}{{ $contact->email ? ' · '.$contact->email : '' }}</option>@endforeach</x-ui.forms.select><x-ui.forms.input-error for="assignContactId" /></div>
                <x-ui.buttons.button-basic type="submit" wire:loading.attr="disabled">Zuordnung bestätigen</x-ui.buttons.button-basic>
            </form>
            @if($customerSuggestions)<p class="mt-3 ops-muted">Mögliche Kunden anhand von Firmenname oder E-Mail-Domain. Die Zuordnung muss bestätigt werden.</p><ul class="mt-2 space-y-2 text-sm">@foreach($customerSuggestions as $suggestion)@if($suggestedCustomer = $customers->firstWhere('id',$suggestion['customer_id']))<li>{{ $suggestedCustomer->company_name }} · {{ implode(', ',array_map(fn($reason)=>['company_name_exact'=>'Firmenname stimmt überein','sender_domain'=>'E-Mail-Domain stimmt überein'][$reason] ?? 'Zuordnung prüfen',$suggestion['reasons'])) }}</li>@endif @endforeach</ul>@endif
            @if(!$selected->customer_id && $canApprove && !$customerId)<div class="mt-3 ops-stack">@if($selected->analysis['customer_draft'] ?? null)<p class="text-sm">Vorbereiteter Kunde: {{ $selected->analysis['customer_draft']['company_name'] ?? 'Firmenname prüfen' }}{{ !empty($selected->analysis['customer_draft']['contact_name']) ? ' · '.$selected->analysis['customer_draft']['contact_name'] : '' }}</p>@endif<x-ui.buttons.button-basic type="button" wire:click="prepareCustomer">Neuen Kunden prüfen und anlegen</x-ui.buttons.button-basic></div>@endif
            </section>
            <section class="border-t border-rt-border pt-3 dark:border-rt-dark-border"><h3 class="font-semibold">Positionen und Planungsvorschläge</h3><p class="mt-2 ops-muted">Freigegebene Vorschläge werden nach der regulären Beauftragung als unbesetzte Schichtentwürfe vorbereitet.</p>
                @forelse($selected->proposals as $proposal)
                    @php($payload = $proposal->payload ?? [])
                    @php($currentProposal = $proposal->source_revision === $selected->source_revision && $selected->revision === $selectedRevision)
                    @php($canCorrect = $currentProposal && !in_array($proposal->status,['applied','stale'],true) && (!$proposal->inquiry || in_array($proposal->inquiry->status,['new','verified'],true)))
                    <article class="mt-4 border-t border-rt-border pt-3 dark:border-rt-dark-border" wire:key="ai-proposal-{{ $proposal->id }}-{{ $proposal->revision }}">
                        <div class="ops-toolbar"><h4 class="font-semibold">{{ $payload['demand']['title'] ?? 'Position '.($proposal->position_index+1) }}</h4><x-operations.status :value="$proposal->status" :label="['proposed'=>'Vorschlag','approved'=>'Freigegeben','applied'=>'Entwürfe erstellt','stale'=>'Erneut prüfen','failed'=>'Übernahme prüfen'][$proposal->status] ?? 'Prüfung nötig'" /></div>
                        <dl class="mt-2 grid gap-2 text-sm sm:grid-cols-2">@foreach(['role_name'=>'Tätigkeit','location_name'=>'Einsatzort','starts_at'=>'Beginn','ends_at'=>'Ende','timezone'=>'Zeitzone','required_staff'=>'Personalbedarf'] as $key=>$label)<div><dt class="ops-muted">{{ $label }}</dt><dd class="break-words">{{ $payload['demand'][$key] ?? 'Noch offen' }}</dd></div>@endforeach</dl>
                        @if($payload['segments'] ?? [])<p class="mt-2 ops-muted">{{ count($payload['segments']) }} ausdrücklich erkannte Schichtabschnitte.</p>@endif
                        @if($payload['raw_requirements'] ?? [])<p class="mt-2 text-sm"><span class="font-semibold">Erkannte Qualifikationsanforderungen:</span> {{ implode(', ', $payload['raw_requirements']) }}</p>@endif
                        @if($payload['unmapped_requirements'] ?? [])<p class="mt-2 ops-muted" role="status">Noch zu prüfen: {{ implode(', ', $payload['unmapped_requirements']) }}. Passende Qualifikationen auswählen und die Prüfung bestätigen.</p>@endif
                        @if($payload['demand']['qualification_ids'] ?? [])<p class="mt-2 text-sm"><span class="font-semibold">Qualifikationen:</span> {{ $qualifications->whereIn('id',$payload['demand']['qualification_ids'])->pluck('name')->implode(', ') }}</p>@endif
                        @if($proposal->inquiry)<x-ui.buttons.button-basic mode="link" :href="\App\Support\Operations\OperationsPages::url('cases',['view'=>'inbox','inquiry'=>$proposal->inquiry_id])" data-no-navigate>Native Anfrage {{ $proposal->inquiry->number }} öffnen</x-ui.buttons.button-basic>@endif
                        <details class="mt-2"><summary class="cursor-pointer text-sm font-semibold">Quellen der erkannten Angaben</summary><dl class="mt-2 space-y-2 text-sm">@forelse(($payload['evidence'] ?? []) as $field=>$evidence)<div><dt class="font-medium">{{ is_array($evidence) ? ($evidence['field'] ?? $field) : $field }}</dt><dd class="break-words ops-muted">{{ is_array($evidence) ? ($evidence['quote'] ?? 'Quelle im Originaleingang prüfen.') : $evidence }} @if(is_array($evidence) && ($evidence['message_id'] ?? null))<span class="block text-xs">Nachricht {{ $evidence['message_id'] }}</span>@endif</dd></div>@empty<p class="ops-muted">Die ursprünglichen Nachrichten und Anlagen stehen unten zur Prüfung bereit.</p>@endforelse</dl></details>
                        @if(!$currentProposal)<p class="mt-2 ops-muted">Ein neuerer Eingang liegt vor. Den aktuellen Vorschlag prüfen.</p>@elseif($proposal->error_code === 'reply_position_review')<p class="mt-2 ops-muted">Diese Antwort muss zuerst einer vorhandenen Position zugeordnet werden.</p>@elseif($proposal->error_code === 'native_workflow_active')<p class="mt-2 ops-muted">Diesen Vorgang in der bestehenden Anfrage prüfen; Angebot oder Beauftragung sind bereits angelaufen.</p>@endif
                        @if($currentProposal && $proposal->status === 'failed' && $proposal->inquiry?->order_id && $canApprove)<div class="ops-actions mt-3"><p class="ops-muted">Der bestätigte Auftrag bleibt erhalten. Die Vorbereitung im Auftrag prüfen oder bei unveränderter Grundlage erneut freigeben.</p><x-ui.buttons.button-basic mode="link" :href="\App\Support\Operations\OperationsPages::url('cases',['view'=>'orders','section'=>'planning','order'=>$proposal->inquiry->order_id])" data-no-navigate>Auftragsplanung öffnen</x-ui.buttons.button-basic><x-ui.buttons.button-basic type="button" wire:click="retryPreparation({{ $proposal->id }},{{ $proposal->revision }})" wire:confirm="Die unveränderte Grundlage prüfen und die Entwurfserstellung erneut freigeben?" wire:loading.attr="disabled" :disabled="!$enabled">Vorbereitung erneut freigeben</x-ui.buttons.button-basic></div>@endif
                        @if($currentProposal && $proposal->error_code === 'reply_position_review')<form wire:submit="mapProposal({{ $proposal->id }},{{ $proposal->revision }})" class="ops-stack mt-3"><x-ui.forms.label :for="'ai-map-'.$proposal->id" value="Vorhandene Anfrage für diese Antwort" /><x-ui.forms.select :id="'ai-map-'.$proposal->id" :wire:model="'mappingInquiryIds.'.$proposal->id"><option value="">Position ausdrücklich zuordnen</option>@foreach(($payload['candidate_inquiry_ids'] ?? []) as $candidateId)@if($candidate = $mappingInquiries->get($candidateId))<option value="{{ $candidate->id }}">{{ $candidate->number }} · {{ $candidate->title }} · {{ $candidate->location_name }}</option>@endif @endforeach</x-ui.forms.select><x-ui.forms.input-error :for="'mappingInquiryIds.'.$proposal->id" /><x-ui.buttons.button-basic type="submit" wire:loading.attr="disabled">Positionszuordnung bestätigen</x-ui.buttons.button-basic></form>@endif
                        @if($editingProposalId === $proposal->id && $canCorrect)
                            <form wire:submit="saveProposal" class="ops-stack mt-3"><div class="ops-form">
                                @foreach(['title'=>'Bezeichnung','role_name'=>'Tätigkeit','location_name'=>'Einsatzort','timezone'=>'Zeitzone'] as $key=>$label)<x-operations.field :label="$label" :model="'proposalForm.demand.'.$key" />@endforeach
                                <x-operations.field label="Beginn" model="proposalForm.demand.starts_at" type="datetime-local" /><x-operations.field label="Ende" model="proposalForm.demand.ends_at" type="datetime-local" /><x-operations.field label="Personalbedarf" model="proposalForm.demand.required_staff" type="number" min="1" max="999" />
                                <fieldset class="ops-full"><legend class="text-sm font-semibold">Erforderliche Qualifikationen</legend><div class="mt-2 grid gap-2 sm:grid-cols-2">@forelse($qualifications as $qualification)<label class="flex items-start gap-2 text-sm"><input type="checkbox" wire:model="proposalForm.demand.qualification_ids" value="{{ $qualification->id }}" class="mt-1 rounded border-rt-border text-rt-red focus:ring-rt-red" /><span>{{ $qualification->name }}</span></label>@empty<p class="ops-muted">Keine aktiven Qualifikationen hinterlegt.</p>@endforelse</div>@if($payload['raw_requirements'] ?? [])<label class="mt-3 flex items-start gap-2 text-sm"><input type="checkbox" wire:model="proposalForm.requirements_reviewed" class="mt-1 rounded border-rt-border text-rt-red focus:ring-rt-red" /><span>Ich habe die erkannten Anforderungen geprüft und den passenden Qualifikationen zugeordnet.</span></label>@endif</fieldset>
                            </div>
                            @foreach(($proposalForm['segments'] ?? []) as $index=>$segment)<fieldset class="ops-form border-t border-rt-border pt-3 dark:border-rt-dark-border" wire:key="segment-{{ $proposal->id }}-{{ $index }}"><legend class="text-sm font-semibold">Schichtabschnitt {{ $index+1 }}</legend><x-operations.field label="Beginn" :model="'proposalForm.segments.'.$index.'.starts_at'" type="datetime-local" /><x-operations.field label="Ende" :model="'proposalForm.segments.'.$index.'.ends_at'" type="datetime-local" /><x-operations.field label="Zeitzone" :model="'proposalForm.segments.'.$index.'.timezone'" /><x-operations.field label="Personalbedarf" :model="'proposalForm.segments.'.$index.'.required_staff'" type="number" min="1" max="999" /><x-operations.field label="Pause (Minuten)" :model="'proposalForm.segments.'.$index.'.planned_break_minutes'" type="number" min="0" /><x-ui.buttons.button-basic type="button" wire:click="removeSegment({{ $index }})">Abschnitt entfernen</x-ui.buttons.button-basic></fieldset>@endforeach
                            <div class="ops-actions"><x-ui.buttons.button-basic type="button" wire:click="addSegment">Abschnitt hinzufügen</x-ui.buttons.button-basic><x-ui.buttons.button-basic type="submit" mode="primary" wire:loading.attr="disabled">Korrektur speichern</x-ui.buttons.button-basic></div>
                            </form>
                        @elseif($canCorrect)<div class="ops-actions mt-3"><x-ui.buttons.button-basic type="button" wire:click="editProposal({{ $proposal->id }})">Angaben korrigieren</x-ui.buttons.button-basic>@if($canApprove && $proposal->status === 'proposed' && $proposal->inquiry && $proposal->inquiry->verified_revision === $proposal->inquiry->revision)<x-ui.buttons.button-basic type="button" mode="primary" wire:click="approveProposal({{ $proposal->id }},{{ $proposal->revision }})" wire:confirm="Diesen Vorschlag zur Entwurfserstellung nach der regulären Beauftragung freigeben?" wire:loading.attr="disabled">Vorschlag freigeben</x-ui.buttons.button-basic>@endif</div>@endif
                    </article>
                @empty<p class="mt-3 ops-muted">Noch keine Positionen ausgewertet.</p>@endforelse
            </section>
            <section class="border-t border-rt-border pt-3 dark:border-rt-dark-border"><h3 class="font-semibold">Nachrichten und Anlagen</h3>
                @foreach($selected->messages as $message)<details class="mt-3" wire:key="ai-message-{{ $message->id }}"><summary class="cursor-pointer text-sm font-semibold">{{ $message->metadata['subject'] ?? 'Originaleingang' }} · {{ $message->created_at->timezone('Europe/Berlin')->format('d.m.Y H:i') }}</summary><p class="mt-2 whitespace-pre-wrap break-words text-sm">{{ $message->body }}</p>@if(($message->metadata['raw_archive_complete'] ?? true) === false || ($message->metadata['text_archive_complete'] ?? true) === false)<p class="mt-2 ops-muted" role="alert">Dieser Eingang überschreitet die Verarbeitungsgrenzen. Das vollständige Original im Postfach manuell prüfen; hier ist ein begrenzter Ausschnitt archiviert.</p>@endif @if($message->raw_path)<x-ui.buttons.button-basic mode="link" :href="route('operations.ai-intake.original',$message->id)" data-no-navigate>{{ ($message->metadata['raw_archive_complete'] ?? true) ? 'Original herunterladen' : 'Archivierten Ausschnitt herunterladen' }}</x-ui.buttons.button-basic>@endif</details>@endforeach
                @foreach($selected->attachments as $attachment)<div class="ops-actions mt-2" wire:key="ai-attachment-{{ $attachment->id }}"><x-ui.buttons.button-basic mode="link" :href="route('operations.ai-intake.attachment',$attachment->id)" data-no-navigate>{{ $attachment->file_name }}</x-ui.buttons.button-basic><span class="ops-muted">{{ number_format($attachment->file_size/1024,0,',','.') }} KB</span></div>@endforeach
            </section>
            <section class="border-t border-rt-border pt-3 dark:border-rt-dark-border"><h3 class="font-semibold">Kundennachrichten und Verarbeitung</h3><p class="mt-2 ops-muted">{{ $selected->question_round }} Rückfragerunden.</p>
                @foreach($selected->deliveries as $delivery)<details class="mt-2" wire:key="ai-delivery-{{ $delivery->id }}"><summary class="cursor-pointer text-sm">{{ \App\Models\AiIntakeDelivery::TYPE_LABELS[$delivery->message_type ?? 'clarification'] ?? 'Kundennachricht' }} · {{ \App\Models\AiIntakeDelivery::STATUS_LABELS[$delivery->status] ?? 'Versand prüfen' }}</summary><p class="mt-2 whitespace-pre-wrap break-words text-sm">{{ $delivery->body }}</p>@if($delivery->status === 'draft')<p class="mt-2 ops-muted">Im AI-Assistenten können Sie Empfänger und Vorlage persönlich freigeben oder verwerfen.</p><x-ui.buttons.button-basic type="button" mode="link" x-on:click="$dispatch('railtime-assistant-open'); $wire.dispatch('operations-assistant-action', { action: 'outbox' })">Kundennachrichten im AI-Assistenten prüfen</x-ui.buttons.button-basic>@elseif($delivery->status === 'unknown')<p class="mt-2 ops-muted">Der Versand wird nicht automatisch wiederholt. Bitte im Dispositionspostfach prüfen, ob die Nachricht gesendet wurde.</p>@endif</details>@endforeach
                @foreach($selected->runs as $run)<p class="mt-2 ops-muted">{{ $run->started_at?->timezone('Europe/Berlin')->format('d.m.Y H:i') }} · {{ ['running'=>'Analyse läuft','completed'=>'Analyse abgeschlossen','succeeded'=>'Verarbeitung abgeschlossen','failed'=>'Analyse prüfen','stale'=>'Stand inzwischen geändert'][$run->status] ?? 'Verarbeitung protokolliert' }}</p>@endforeach
            </section>
        @endif
    </x-operations.modal>
    @if($customerDraftOpen && $selectedId)<livewire:admin.operations.customers :embedded="true" :modal-only="true" :start-creating="true" :workspace-revision="$selectedRevision" :draft-intake-id="$selectedId" :key="'ai-customer-draft-'.$selectedId.'-'.$selectedRevision" />@endif
</section>
