<section class="rt-customer-portal__manage rt-ops" aria-label="Kundenportalverwaltung">
    @unless($embedded)<header class="rt-customer-portal__manage-top"><div class="space-y-1.5"><x-ui.forms.label for="portal-management-customer" value="Kunde" /><x-ui.forms.select id="portal-management-customer" change="$wire.selectCustomer(Number($event.target.value))">@forelse($customers as $entry)<option value="{{ $entry->id }}" @selected($entry->id===$customerId)>{{ $entry->company_name }}</option>@empty<option value="">Keine betreuten Kunden</option>@endforelse</x-ui.forms.select></div>@if($customer)<span class="rt-customer-portal__status">{{ $setting?->enabled?'Portal freigeschaltet':'Portal deaktiviert' }}</span>@endif</header>@endunless
    <x-operations.feedback />
    @if(!$customer)<p class="ops-muted">Keine betreuten Kunden.</p>@else
        @unless($embedded)<nav class="rt-customer-portal__manage-tabs" aria-label="Portalverwaltung">@foreach($this::TABS as $key=>$label)@continue($key==='automation' && !$this->canCustomer('customers.portal.automation'))@continue($key==='publications' && !$this->canCustomer('customers.portal.publish'))<x-ui.buttons.button-basic type="button" :mode="$tab===$key?'primary':'link'" wire:click="setTab('{{ $key }}')" :aria-current="$tab===$key?'page':null">{{ $label }}</x-ui.buttons.button-basic>@endforeach</nav>@endunless
        <x-tables.toolbar :title="$this::TABS[$tab]" id="portal-management-filters"><x-slot:search><x-tables.search-field wire:model.live.debounce.300ms="search" placeholder="Vorgang suchen" /></x-slot:search><x-slot:bulk>
            @if($tab==='access')<div class="ops-actions"><x-ui.buttons.button-basic type="button" mode="primary" wire:click="edit('access')">Zugang einstellen</x-ui.buttons.button-basic>@if($embedded)<x-ui.buttons.button-basic type="button" wire:click="edit('contact')">Kontakt berechtigen</x-ui.buttons.button-basic>@endif</div>
            @elseif($tab==='contacts')<x-ui.buttons.button-basic type="button" mode="primary" wire:click="edit('contact')">Kontakt berechtigen</x-ui.buttons.button-basic>
            @elseif($tab==='automation')<div class="ops-actions"><x-ui.buttons.button-basic type="button" mode="primary" wire:click="edit('profile')" can="customers.portal.automation">Regelprofil</x-ui.buttons.button-basic><x-ui.buttons.button-basic type="button" wire:click="edit('commitment')" can="employees.master-data.view">Kontingent anfragen</x-ui.buttons.button-basic></div>
            @elseif($tab==='publications')<div class="ops-actions"><x-ui.buttons.button-basic type="button" mode="primary" wire:click="edit('publish')" can="customers.portal.publish">Stand freigeben</x-ui.buttons.button-basic><x-ui.buttons.button-basic type="button" wire:click="edit('document')" can="customers.portal.publish">Dokument hochladen</x-ui.buttons.button-basic></div>@elseif($tab==='requests')<x-ui.buttons.button-basic type="button" wire:click="edit('reply')" can="customers.portal.publish">Nachricht an Kunden</x-ui.buttons.button-basic>@endif
        </x-slot:bulk></x-tables.toolbar>
        @if($tab==='access')<section class="ops-panel"><dl class="rt-customer-portal__details"><div><dt>Portalzugang</dt><dd>{{ $setting?->enabled?'Freigeschaltet':'Deaktiviert' }}</dd></div><div><dt>Benannte Kontakte</dt><dd class="tabular-nums">{{ $items->count() }}</dd></div><div><dt>Automatik</dt><dd>{{ ['manual'=>'Manuelle Prüfung','offer'=>'Angebotsassistenz','accept'=>'Regelgebundene Zusage','assist'=>'Angebotsassistenz','automatic'=>'Regelgebundene Zusage'][$setting?->automation_mode ?? 'manual'] ?? 'Manuelle Prüfung' }}</dd></div><div><dt>Revision</dt><dd class="tabular-nums">{{ $setting?->revision ?? 0 }}</dd></div></dl></section>@endif
        <x-tables.table :items="$items" :columns="array_values(array_filter([['label'=>$tab==='contacts' || $tab==='access'?'Kontakt':'Vorgang','key'=>'title','width'=>'2fr'],in_array($tab,['contacts','access'])?['label'=>'Rolle','key'=>'role']:null,['label'=>'Status','key'=>'status'],['label'=>'Stand','key'=>'revision'],['label'=>'Aktionen','key'=>'actions','width'=>'1.5fr']]))" :table-key="'portal-management-'.$customerId.'-'.$tab" row-view="components.tables.rows.customer-portal.management" empty="Keine Einträge." />
        @if($tab==='automation')<section><h2 class="text-base font-semibold">Verbindliche Kontingente</h2><x-tables.table :items="$commitments" :columns="[['label'=>'Mitarbeiter / Tätigkeit','key'=>'title','width'=>'2fr'],['label'=>'Status','key'=>'status'],['label'=>'Stand','key'=>'revision'],['label'=>'Aktion','key'=>'actions']]" :table-key="'portal-commitment-'.$customerId" row-view="components.tables.rows.customer-portal.management" empty="Keine Kontingente." /></section>@endif
        @if($simulation)<section class="ops-panel"><h3 class="text-base font-semibold">Prüfergebnis</h3><p class="mt-2 text-sm">{{ $simulation['message'] ?? $simulation['reason'] ?? $simulation['status'] ?? 'Prüfung abgeschlossen' }}</p>@foreach($simulation['issues'] ?? [] as $issue)<p class="text-sm">{{ is_array($issue)?($issue['message'] ?? $issue['code'] ?? ''):$issue }}</p>@endforeach</section>@endif
        <div class="hidden"><x-operations.modal wire:model="formOpen" :title="match($modal){'access'=>'Portalzugang','contact'=>'Kontaktrechte','invite'=>'Einladung bestätigen','revoke'=>'Zugang widerrufen','profile'=>'Automatikprofil','approve-profile'=>'Profil freigeben','commitment'=>'Kontingent anfragen','approve-commitment'=>'Kontingent freigeben','review-request'=>'Anliegen bearbeiten','reply'=>'Kundennachricht','publish'=>'Kundenstand freigeben','document'=>'Dokument hochladen','review-document'=>'Dokument prüfen','withdraw'=>'Freigabe zurückziehen','decision'=>'Anfrage entscheiden',default=>'Kundenportal'}" max-width="4xl">
            @if($formOpen)<form wire:submit="save" class="ops-form">
                @if($modal==='access')
                    <div class="ops-full"><x-ui.forms.checkbox wire:model="form.enabled" label="Portal für diesen Kunden freischalten" /></div>
                    <x-operations.field label="Einladungsempfänger bei Neuaktivierung" model="form.contact_id" type="select"><option value="">Benannten Kontakt auswählen</option>@foreach($contacts as $contact)<option value="{{ $contact->id }}">{{ $contact->name }} · {{ $contact->email }}</option>@endforeach</x-operations.field>
                    <div class="ops-full rt-customer-portal__checkgroup">@foreach(\App\Models\CustomerPortalSetting::MODULES as $module)<x-ui.forms.checkbox wire:model="form.modules" :value="$module" :label="['orders'=>'Aufträge','requests'=>'Leistungsanfragen','offers'=>'Angebote','changes'=>'Änderungsanfragen','proofs'=>'Leistungsabnahmen','documents'=>'Dokumente','messages'=>'Nachrichten','reports'=>'Berichte'][$module]" />@endforeach</div>
                    <div class="ops-full rt-customer-portal__scope"><h3 class="text-sm font-semibold">Mitteilungen</h3><div class="mt-3 rt-customer-portal__checkgroup">@foreach(['requests'=>'Anfragen','decisions'=>'Entscheidungen','orders'=>'Aufträge','proofs'=>'Leistungen','documents'=>'Dokumente','messages'=>'Nachrichten'] as $value=>$label)<x-ui.forms.checkbox wire:model="form.notifications" :value="$value" :label="$label" />@endforeach</div></div>
                    <div class="ops-full"><x-ui.forms.checkbox wire:model="form.require_mfa" label="Zusätzliche Bestätigung bei Bestellungen und Abnahmen" /></div>
                    <div class="ops-full"><x-ui.forms.checkbox wire:model="form.booking_authority" label="Rahmenbuchungen mit Bestellrecht zulassen" /></div>
                    <x-operations.field label="Anfrageautomatik" model="form.automation_mode" type="select"><option value="manual">Manuelle Prüfung</option><option value="offer">Automatisches Angebot</option><option value="accept">Regelgebundene Zusage</option></x-operations.field>
                    <div class="ops-full"><x-ui.forms.checkbox wire:model="form.auto_reject" label="Geprüfte Ausschlüsse für automatische Absagen zulassen" /></div>
                    <div class="ops-full"><x-ui.forms.checkbox wire:model="form.confirmed" :label="'Änderung für '.$customer->company_name.' und benannten Empfänger bestätigen'" /></div>
                @elseif($modal==='contact')
                    @if(!$recordId)<x-operations.field label="Kundenkontakt" model="form.contact_id" type="select" required><option value="">Auswählen</option>@foreach($contacts as $contact)<option value="{{ $contact->id }}">{{ $contact->name }} · {{ $contact->email }}</option>@endforeach</x-operations.field>@else<p class="ops-full text-sm">{{ $form['email'] ?? '' }}</p>@endif
                    <x-operations.field label="Rolle" model="form.role" type="select">@foreach($this::ROLES as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</x-operations.field>
                    <x-operations.field label="Zugang" model="form.status" type="select"><option value="pending">Einladung ausstehend</option><option value="active">Aktiv · Einladung bereits angenommen</option><option value="suspended">Pausiert</option></x-operations.field>
                    <x-operations.field label="Historie ab" model="form.history_from" type="date" />
                    <fieldset class="ops-full rt-customer-portal__checkgroup"><legend class="text-sm font-semibold">Einsatzorte · leer = alle freigegebenen Orte</legend>@foreach($locations as $location)<x-ui.forms.checkbox wire:model="form.location_ids" :value="$location->id" :label="$location->name" />@endforeach</fieldset>
                    <div class="ops-full"><x-ui.forms.checkbox wire:model="form.confirmed" label="Kontaktrechte ausdrücklich bestätigen" /></div>
                @elseif(in_array($modal,['invite','revoke']))
                    <p class="ops-full text-sm font-semibold">{{ $form['email'] ?? '' }}</p><div class="ops-full"><x-ui.forms.checkbox wire:model="form.confirmed" :label="$modal==='invite'?'Einladung an diesen Empfänger bestätigen':'Zugang dieses Kontakts widerrufen'" /></div>
                @elseif($modal==='profile')
                    <x-operations.field label="Name" model="form.name" maxlength="180" required /><x-operations.field label="Modus" model="form.mode" type="select"><option value="manual">Manuelle Prüfung</option><option value="offer">Automatisches Angebot</option><option value="accept">Regelgebundene Zusage</option></x-operations.field>
                    <x-operations.field label="Gültig ab" model="form.valid_from" type="date" required /><x-operations.field label="Gültig bis" model="form.valid_until" type="date" />
                    <x-operations.field label="Mindestvorlauf (min)" model="form.minimum_lead_minutes" type="number" min="0" max="525600" /><x-operations.field label="Maximaler Personalbedarf" model="form.maximum_staff" type="number" min="1" max="999" />
                    <x-operations.field label="Bestelllimit (EUR)" model="form.maximum_total" type="number" min="0" max="99999999" step="0.01" />
                    <x-operations.field label="Freigegebene Tätigkeiten · eine je Zeile" model="form.allowed_roles" type="textarea" :wide="true" required />
                    <fieldset class="ops-full rt-customer-portal__checkgroup"><legend class="text-sm font-semibold">Freigegebene Einsatzorte</legend>@foreach($locations as $location)<x-ui.forms.checkbox wire:model="form.location_ids" :value="$location->id" :label="$location->name" />@endforeach</fieldset>
                    <fieldset class="ops-full rt-customer-portal__checkgroup"><legend class="text-sm font-semibold">Freigegebene Konditionen</legend>@foreach($conditions as $condition)<x-ui.forms.checkbox wire:model="form.condition_ids" :value="$condition->id" :label="$condition->label.' · '.$condition->unit.' · '.$condition->valid_from->format('d.m.Y')" />@endforeach</fieldset>
                    <div class="ops-full"><x-ui.forms.checkbox wire:model="form.auto_reject" label="Eindeutige ausgeschlossene Tätigkeiten oder Orte automatisch absagen" /></div>
                @elseif($modal==='approve-profile')<p class="ops-full text-sm font-semibold">{{ $form['name'] ?? '' }} · Revision {{ $revision }}</p><div class="ops-full"><x-ui.forms.checkbox wire:model="form.confirmed" label="Geprüftes Profil als zweiter Verantwortlicher freigeben" /></div>
                @elseif($modal==='commitment')<x-operations.field label="Mitarbeiter" model="form.user_id" type="select" required><option value="">Auswählen</option>@foreach($staff as $person)<option value="{{ $person->id }}">{{ $person->name }}</option>@endforeach</x-operations.field><x-operations.field label="Tätigkeit" model="form.role_name" required /><x-operations.field label="Einsatzort" model="form.location_id" type="select" required><option value="">Auswählen</option>@foreach($locations as $location)<option value="{{ $location->id }}">{{ $location->name }}</option>@endforeach</x-operations.field><x-operations.field label="Zeitzone" model="form.timezone" required /><x-operations.field label="Beginn" model="form.starts_at" type="datetime-local" required /><x-operations.field label="Ende" model="form.ends_at" type="datetime-local" required /><x-operations.field label="Planpause (min)" model="form.planned_break_minutes" type="number" min="0" max="1440" required /><fieldset class="ops-full rt-customer-portal__checkgroup"><legend class="text-sm font-semibold">Zwingende Nachweise</legend>@foreach($qualifications as $qualification)<x-ui.forms.checkbox wire:model="form.qualification_ids" :value="$qualification->id" :label="$qualification->name" />@endforeach</fieldset>
                @elseif($modal==='approve-commitment')<p class="ops-full text-sm font-semibold">{{ $form['role_name'] }} · {{ $form['starts_at'] }} – {{ $form['ends_at'] }}</p><div class="ops-full"><x-ui.forms.checkbox wire:model="form.confirmed" label="Zugestimmtes Kontingent nach frischer Prüfung verbindlich freigeben" /></div>
                @elseif($modal==='review-request')<p class="ops-full text-sm font-semibold">{{ $form['title'] }}</p><p class="ops-full text-sm whitespace-pre-line">{{ $form['message'] }}</p><x-operations.field label="Status" model="form.status" type="select"><option value="reviewing">In Bearbeitung</option><option value="resolved">Erledigt</option><option value="rejected">Abgelehnt</option></x-operations.field><x-operations.field label="Kundenantwort" model="form.response" type="textarea" :wide="true" required minlength="5" maxlength="5000" />
                @elseif($modal==='reply')<x-operations.field label="Betreff" model="form.subject" required maxlength="180" /><x-operations.field label="Auftrags-ID" model="form.order_id" type="number" min="1" /><x-operations.field label="Nachricht" model="form.body" type="textarea" :wide="true" required maxlength="5000" />
                @elseif($modal==='publish')
                    <x-operations.field label="Geschäftsstand" model="form.target" type="select" required><option value="">Auswählen</option>@foreach($targets as $target)<option value="{{ $target['type'].':'.$target['id'] }}">{{ $target['label'] }}</option>@endforeach</x-operations.field>
                    <x-operations.field label="Einsatzort" model="form.location_id" type="select"><option value="">Alle freigegebenen Orte</option>@foreach($locations as $location)<option value="{{ $location->id }}">{{ $location->name }}</option>@endforeach</x-operations.field><x-operations.field label="Kundenhinweis" model="form.summary" type="textarea" :wide="true" maxlength="2000" /><div class="ops-full"><x-ui.forms.checkbox wire:model="form.confirmed" label="Diesen Stand für den Kunden veröffentlichen" /></div>
                @elseif($modal==='document')
                    <x-operations.field label="Bezeichnung" model="form.title" required maxlength="180" /><x-operations.field label="Art" model="form.kind" type="select"><option value="document">Dokument</option><option value="invoice">Rechnungsdokument</option></x-operations.field><x-operations.field label="Auftrags-ID" model="form.order_id" type="number" min="1" /><x-operations.field label="Einsatzort" model="form.location_id" type="select"><option value="">Alle freigegebenen Orte</option>@foreach($locations as $location)<option value="{{ $location->id }}">{{ $location->name }}</option>@endforeach</x-operations.field><div class="ops-full space-y-1.5"><x-ui.forms.label for="portal-document-upload" value="PDF / Bild · max. 10 MB" /><x-ui.forms.input id="portal-document-upload" type="file" wire:model="upload" accept=".pdf,.jpg,.jpeg,.png" required /><x-ui.forms.input-error for="upload" /></div>
                @elseif(in_array($modal,['review-document','review-attachment']))<p class="ops-full text-sm font-semibold">{{ $form['title'] ?? '' }}</p>
                    @if($modal==='review-attachment' && \Illuminate\Support\Facades\Route::has('customer-portal.manager.attachment'))<div class="ops-full"><a class="rt-ui-button rt-ui-button-secondary" href="{{ route('customer-portal.manager.attachment',['id'=>$recordId]) }}">Datei prüfen</a></div>@endif
                    @if($modal==='review-document' && \Illuminate\Support\Facades\Route::has('customer-portal.manager.document'))<div class="ops-full"><a class="rt-ui-button rt-ui-button-secondary" href="{{ route('customer-portal.manager.document',['id'=>$recordId]) }}">Datei prüfen</a></div>@endif
                    <x-operations.field label="Prüfvermerk" model="form.note" type="textarea" :wide="true" required minlength="5" maxlength="2000" /><div class="ops-full"><x-ui.forms.checkbox wire:model="form.confirmed" label="Datei auf Inhalt und Sicherheit geprüft; Freigabe bestätigen" /></div>
                @elseif($modal==='withdraw')<p class="ops-full text-sm font-semibold">{{ $form['title'] ?? '' }}</p><x-operations.field label="Grund" model="form.reason" type="textarea" :wide="true" required minlength="5" maxlength="2000" />
                @elseif($modal==='decision')<p class="ops-full text-sm font-semibold">{{ $form['title'] ?? '' }}</p><x-operations.field label="Entscheidung" model="form.action" type="select"><option value="review">In Prüfung</option><option value="offer">Angebot</option><option value="accept">Leistungszusage</option><option value="reject">Absage</option></x-operations.field><x-operations.field label="Kundenrückmeldung" model="form.note" type="textarea" :wide="true" required minlength="5" maxlength="5000" />@endif
                <div class="ops-full ops-actions"><x-ui.buttons.button-basic type="submit" mode="primary" wire:loading.attr="disabled">{{ match($modal){'invite'=>'Einladung vormerken','revoke'=>'Widerrufen','approve-profile'=>'Freigeben','access'=>'Bestätigt speichern',default=>'Speichern'} }}</x-ui.buttons.button-basic><x-ui.buttons.button-basic type="button" wire:click="close">Abbrechen</x-ui.buttons.button-basic></div>
            </form>@endif
        </x-operations.modal></div>
    @endif
</section>
