@section('title', 'Dashboard')
<x-ui.page :auto-intro="false" :welcome-intro="false" content-class="rt-ops ops-stack" data-native-dashboard>
    @if($hasOperations)<livewire:operations.cockpit />@endif
    @if($hasPersonalWork)
        @if($hasOperations)<details class="ops-panel"><summary>Mein Arbeitstag</summary><livewire:operations.my-work /></details>
        @else<header class="ops-toolbar"><div><p class="ops-kicker">{{ now(config('operations.display_timezone'))->translatedFormat('l, d. F') }}</p><h1>Mein Arbeitstag</h1></div><span class="ops-muted">{{ auth()->user()->name }}</span></header><livewire:operations.my-work />@endif
    @endif
    <div class="ops-split"><section class="ops-panel"><header class="ops-toolbar"><h2>Meine Ablage</h2><a class="ops-link" href="{{ route('files') }}" wire:navigate>{{ $filesTotal }} Dateien →</a></header>@forelse($recentFiles as $file)<div class="ops-row"><span>{{ $file->name ?? $file->title ?? 'Datei' }}</span><a class="ops-link" href="{{ route('files') }}" wire:navigate>Öffnen</a></div>@empty<div class="ops-empty">Keine Dateien.</div>@endforelse</section><section class="ops-panel ops-stack"><header class="ops-toolbar"><h2>Nachrichten</h2><span class="ops-badge">{{ $unreadMessages }} ungelesen</span></header><a class="ops-link" href="{{ route('messages') }}" wire:navigate>Posteingang öffnen →</a><div class="ops-row"><h3>{{ $deviceWidget['scope'] === 'fleet' ? 'Geräte & Lager' : 'Meine Geräte' }}</h3>@if($deviceWidget['href'])<a class="ops-link" href="{{ $deviceWidget['href'] }}" wire:navigate>{{ $deviceWidget['stats']['total'] }} Geräte →</a>@else<span class="ops-muted">Nicht verfügbar</span>@endif</div><a class="ops-link" href="{{ route(auth()->user()->isAdmin() ? 'admin.operations.wagon-list' : 'operations.wagon-list') }}" wire:navigate>Wagenliste öffnen →</a></section></div>
    @if($canViewSystemData)<details class="ops-panel"><summary wire:click="loadSystemData">System</summary>@if($systemLoaded && $system)<dl class="ops-meta">@foreach(['appVersion'=>'Anwendung','environment'=>'Umgebung','php'=>'PHP','database'=>'Datenbank','queue'=>'Queue','lastActivity'=>'Letzte Aktivität','storage'=>'Dateispeicher','disk'=>'Datenträger'] as $key=>$label)<div><dt>{{ $label }}</dt><dd>{{ $system[$key] ?? '—' }}</dd></div>@endforeach</dl>@endif</details>@endif
</x-ui.page>
