<div class="rt-ops ops-stack" data-personal-workspace wire:poll.60s>
    <nav class="ops-tabs ops-personal-tabs" aria-label="Mein Arbeitsplatz">@foreach(['today'=>'Mein Tag','schedule'=>'Dienstplan','time'=>'Meine Zeit','records'=>'Nachweise'] as $key=>$label)<button type="button" wire:click="showTab('{{ $key }}')" aria-pressed="{{ $tab === $key ? 'true' : 'false' }}">{{ $label }}</button>@endforeach</nav>
    <x-operations.feedback />
    @if(in_array($tab, ['today','time']) && $activeTime)
        <section class="ops-panel ops-service ops-stack" aria-label="Laufende Zeiterfassung" wire:poll.15s><header class="ops-toolbar"><div><p class="ops-kicker">Seit {{ $activeTime->starts_at->format('H:i') }} · {{ $activeTime->timezone }}</p><h2>{{ $activeTime->plan_snapshot['title'] }}</h2></div><x-operations.status :value="$activeTime->status" /></header><p class="ops-clock">{{ \App\Support\Operations\OperationsDateTime::duration($activeTime->netSeconds()) }}</p><div class="ops-actions">@if($activeTime->status === 'running')<x-ui.buttons.button-basic wire:click="clock({{ $activeTime->id }},{{ $activeTime->revision }},'pause')" wire:loading.attr="disabled">Pause starten</x-ui.buttons.button-basic>@else<x-ui.buttons.button-basic mode="primary" wire:click="clock({{ $activeTime->id }},{{ $activeTime->revision }},'resume')" wire:loading.attr="disabled">Weiterarbeiten</x-ui.buttons.button-basic>@endif<x-ui.buttons.button-basic wire:click="clock({{ $activeTime->id }},{{ $activeTime->revision }},'stop')" wire:confirm="Zeiterfassung beenden?" wire:loading.attr="disabled">Dienst beenden</x-ui.buttons.button-basic></div></section>
    @endif
    @if(in_array($tab, ['today','schedule']))
        <header class="ops-toolbar"><h2>{{ $tab === 'today' ? 'Nächste Dienste' : $from->format('d.m.').' – '.$to->copy()->subDay()->format('d.m.Y') }}</h2>@if($tab === 'schedule')<div class="ops-actions"><x-ui.buttons.button-basic wire:click="$set('week', {{ max(-12,$week-1) }})" aria-label="Vorherige Woche">←</x-ui.buttons.button-basic><x-ui.buttons.button-basic wire:click="$set('week', 0)">Heute</x-ui.buttons.button-basic><x-ui.buttons.button-basic wire:click="$set('week', {{ min(52,$week+1) }})" aria-label="Nächste Woche">→</x-ui.buttons.button-basic></div>@endif</header>
        <x-tables.table :columns="[['label'=>'Dienstplan','key'=>'shift']]" :items="$assignments" row-view="components.tables.rows.operations.personal-shift" empty="Keine veröffentlichten Dienste in diesem Zeitraum." />
        @if($tab === 'today' && $times->contains(fn($entry) => in_array($entry->status,['completed','returned'],true)))<button class="ops-panel ops-toolbar" type="button" wire:click="showTab('time')"><strong>Zeitmeldungen bearbeiten</strong><span class="ops-link">Öffnen →</span></button>@endif
    @elseif($tab === 'time')
        <h2>Meine Zeitmeldungen</h2>
        @if($manualAssignments->isNotEmpty())
            <x-ui.buttons.button-basic wire:click="openForm('manual')">Zeit nachtragen</x-ui.buttons.button-basic><x-operations.modal wire:model="manualOpen" title="Zeit nachtragen"><form wire:submit="saveManual" class="ops-form">
                <x-operations.field label="Dienst" model="manualAssignmentId" type="select" :wide="true" required><option value="">Dienst auswählen</option>@foreach($manualAssignments as $item)<option value="{{ $item->id }}">{{ $item->shift->starts_at->format('d.m.Y') }} · {{ $item->shift->title }} · {{ $item->shift->timezone }}</option>@endforeach</x-operations.field>
                <x-operations.field label="Beginn · Dienstzeitzone" model="manualTime.starts_at" type="datetime-local" required /><x-operations.field label="Ende · Dienstzeitzone" model="manualTime.ends_at" type="datetime-local" required /><x-operations.field label="Pause (min)" model="manualTime.pause_minutes" type="number" min="0" required /><x-operations.field label="Grund des Nachtrags" model="manualTime.note" required minlength="5" /><div class="ops-full"><x-ui.buttons.button-basic mode="primary" type="submit" wire:loading.attr="disabled">Nachtrag speichern</x-ui.buttons.button-basic></div>
            </form></x-operations.modal>
        @endif
        <x-operations.modal wire:model="correctionOpen" title="Zeit korrigieren"><form wire:submit="correct" class="ops-panel ops-form"><h3 class="ops-full">Zeit korrigieren</h3><x-operations.field label="Beginn" model="correction.starts_at" type="datetime-local" required /><x-operations.field label="Ende" model="correction.ends_at" type="datetime-local" required /><x-operations.field label="Pause (min)" model="correction.pause_minutes" type="number" min="0" required /><x-operations.field label="Korrekturgrund" model="correction.note" required minlength="5" /><div class="ops-full ops-actions"><x-ui.buttons.button-basic type="submit" mode="primary" wire:loading.attr="disabled">Korrektur speichern</x-ui.buttons.button-basic><x-ui.buttons.button-basic wire:click="cancelCorrection">Abbrechen</x-ui.buttons.button-basic></div></form></x-operations.modal>
        <x-tables.table :columns="[['label'=>'Zeitmeldung','key'=>'entry']]" :items="$times" row-view="components.tables.rows.operations.personal-time" empty="Noch keine Zeitmeldungen." />{{ $times->links() }}
    @else
        <div class="ops-split"><section class="ops-stack"><header class="ops-toolbar"><h2>Meine Nachweise</h2></header><x-ui.buttons.button-basic wire:click="openForm('qualification')">Nachweis einreichen</x-ui.buttons.button-basic><x-operations.modal wire:model="qualificationOpen" title="Nachweis einreichen"><form wire:submit="upload" class="ops-form"><x-operations.field label="Nachweisart" model="qualification.qualification_type_id" type="select" required :wide="true"><option value="">Auswählen</option>@foreach($types as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</x-operations.field><x-operations.field label="Gültig ab" model="qualification.valid_from" type="date" required /><x-operations.field label="Gültig bis" model="qualification.valid_until" type="date" required /><x-operations.field label="Datei · PDF, JPG oder PNG · max. 10 MB" model="evidence" type="file" accept="application/pdf,image/jpeg,image/png" required :wide="true" /><div class="ops-full"><x-ui.buttons.button-basic mode="primary" type="submit" wire:loading.attr="disabled">Einreichen</x-ui.buttons.button-basic></div></form></x-operations.modal><x-tables.table :columns="[['label'=>'Nachweis','key'=>'record']]" :items="$qualifications" row-view="components.tables.rows.operations.personal-qualification" empty="Keine Nachweise eingereicht." />{{ $qualifications->links() }}</section>
        <section class="ops-stack"><h2>Meine Abwesenheiten</h2><x-ui.buttons.button-basic wire:click="openForm('absence')">Abwesenheit beantragen</x-ui.buttons.button-basic><x-operations.modal wire:model="absenceOpen" title="Abwesenheit beantragen"><form wire:submit="requestAbsence" class="ops-form"><x-operations.field label="Art" model="absence.kind" type="select"><option value="vacation">Urlaub</option><option value="unavailable">Nicht verfügbar</option><option value="other">Abwesenheit</option></x-operations.field><x-operations.field label="Zeitzone" model="absence.timezone" required /><x-operations.field label="Beginn" model="absence.starts_at" type="datetime-local" required /><x-operations.field label="Ende" model="absence.ends_at" type="datetime-local" required /><x-operations.field label="Notiz (optional)" model="absence.note" maxlength="1000" :wide="true" /><div class="ops-full"><x-ui.buttons.button-basic mode="primary" type="submit" wire:loading.attr="disabled">Antrag einreichen</x-ui.buttons.button-basic></div></form></x-operations.modal><x-tables.table :columns="[['label'=>'Abwesenheit','key'=>'record']]" :items="$absences" row-view="components.tables.rows.operations.personal-absence" empty="Keine Abwesenheiten." />{{ $absences->links() }}</section></div>
    @endif
</div>
