<div class="rt-ops ops-stack" data-personal-workspace wire:poll.60s>
    <nav class="ops-tabs ops-personal-tabs" aria-label="Mein Arbeitsplatz">@foreach(['today'=>'Mein Tag','schedule'=>'Dienstplan','time'=>'Meine Zeit','records'=>'Nachweise'] as $key=>$label)<button type="button" wire:click="showTab('{{ $key }}')" aria-pressed="{{ $tab === $key ? 'true' : 'false' }}">{{ $label }}</button>@endforeach</nav>
    <x-operations.feedback />
    @if(in_array($tab, ['today','time']) && $activeTime)
        <section class="ops-panel ops-service ops-stack" aria-label="Laufende Zeiterfassung" wire:poll.15s><header class="ops-toolbar"><div><p class="ops-kicker">Seit {{ $activeTime->starts_at->format('H:i') }} · {{ $activeTime->timezone }}</p><h2>{{ $activeTime->plan_snapshot['title'] }}</h2></div><x-operations.status :value="$activeTime->status" /></header><p class="ops-clock">{{ \App\Support\Operations\OperationsDateTime::duration($activeTime->netSeconds()) }}</p><div class="ops-actions">@if($activeTime->status === 'running')<x-ui.buttons.button-basic wire:click="clock({{ $activeTime->id }},{{ $activeTime->revision }},'pause')" wire:loading.attr="disabled">Pause starten</x-ui.buttons.button-basic>@else<x-ui.buttons.button-basic mode="primary" wire:click="clock({{ $activeTime->id }},{{ $activeTime->revision }},'resume')" wire:loading.attr="disabled">Weiterarbeiten</x-ui.buttons.button-basic>@endif<x-ui.buttons.button-basic wire:click="clock({{ $activeTime->id }},{{ $activeTime->revision }},'stop')" wire:confirm="Zeiterfassung beenden?" wire:loading.attr="disabled">Dienst beenden</x-ui.buttons.button-basic></div></section>
    @endif
    @if(in_array($tab, ['today','schedule']))
        <header class="ops-toolbar"><h2>{{ $tab === 'today' ? 'Nächste Dienste' : $from->format('d.m.').' – '.$to->copy()->subDay()->format('d.m.Y') }}</h2>@if($tab === 'schedule')<div class="ops-actions"><x-ui.buttons.button-basic wire:click="$set('week', {{ max(-12,$week-1) }})" aria-label="Vorherige Woche">←</x-ui.buttons.button-basic><x-ui.buttons.button-basic wire:click="$set('week', 0)">Heute</x-ui.buttons.button-basic><x-ui.buttons.button-basic wire:click="$set('week', {{ min(52,$week+1) }})" aria-label="Nächste Woche">→</x-ui.buttons.button-basic></div>@endif</header>
        <section class="ops-service-grid">
            @forelse($assignments as $assignment)
                @php($shift = $assignment->shift)
                <article class="ops-panel ops-service ops-stack" wire:key="my-shift-{{ $assignment->id }}"><header class="ops-toolbar"><div><p class="ops-service-date">{{ $shift->starts_at->translatedFormat('D, d. M') }} · {{ $shift->starts_at->format('H:i') }} – {{ $shift->ends_at->format($shift->starts_at->isSameDay($shift->ends_at) ? 'H:i' : 'd.m. H:i') }}</p><h2>{{ $shift->title }}</h2></div><x-operations.status :value="$assignment->status->value" /></header><p>{{ $shift->location_name }} <span class="ops-muted">· {{ $shift->role_name }} · {{ $shift->timezone }}</span></p><p class="ops-muted">{{ $shift->order?->customer?->company_name }} · {{ $shift->order?->order_number }} · {{ $shift->planned_break_minutes }} min Pause</p>
                    @if($assignment->plan_is_stale)<span class="ops-badge" data-state="pending">Planänderung in Prüfung</span>@elseif($assignment->status->value === 'requested')<div class="ops-actions"><x-ui.buttons.button-basic mode="primary" wire:click="respond({{ $assignment->id }},{{ $shift->revision }},true)" wire:loading.attr="disabled">Dienst bestätigen</x-ui.buttons.button-basic><x-ui.buttons.button-basic wire:click="respond({{ $assignment->id }},{{ $shift->revision }},false)" wire:confirm="Dienst ablehnen?" wire:loading.attr="disabled">Ablehnen</x-ui.buttons.button-basic></div>
                    @elseif(!$activeTime && !$assignment->timeEntry && now()->utc()->gte($shift->starts_at->subMinutes(config('operations.clock_start_early_minutes'))) && now()->utc()->lt($shift->ends_at))<div><x-ui.buttons.button-basic mode="primary" wire:click="start({{ $assignment->id }},{{ $shift->revision }})" wire:loading.attr="disabled">Dienst starten</x-ui.buttons.button-basic></div>@endif

                </article>
            @empty<div class="ops-panel ops-empty">Keine veröffentlichten Dienste in diesem Zeitraum.</div>@endforelse
        </section>
        @if($tab === 'today' && $times->contains(fn($entry) => in_array($entry->status,['completed','returned'],true)))<button class="ops-panel ops-toolbar" type="button" wire:click="showTab('time')"><strong>Zeitmeldungen bearbeiten</strong><span class="ops-link">Öffnen →</span></button>@endif
    @elseif($tab === 'time')
        <h2>Meine Zeitmeldungen</h2>
        @if($manualAssignments->isNotEmpty())
            <details class="ops-panel"><summary>Zeit nachtragen</summary><form wire:submit="saveManual" class="ops-form">
                <x-operations.field label="Dienst" model="manualAssignmentId" type="select" :wide="true" required><option value="">Dienst auswählen</option>@foreach($manualAssignments as $item)<option value="{{ $item->id }}">{{ $item->shift->starts_at->format('d.m.Y') }} · {{ $item->shift->title }} · {{ $item->shift->timezone }}</option>@endforeach</x-operations.field>
                <x-operations.field label="Beginn · Dienstzeitzone" model="manualTime.starts_at" type="datetime-local" required /><x-operations.field label="Ende · Dienstzeitzone" model="manualTime.ends_at" type="datetime-local" required /><x-operations.field label="Pause (min)" model="manualTime.pause_minutes" type="number" min="0" required /><x-operations.field label="Grund des Nachtrags" model="manualTime.note" required minlength="5" /><div class="ops-full"><x-ui.buttons.button-basic mode="primary" type="submit" wire:loading.attr="disabled">Nachtrag speichern</x-ui.buttons.button-basic></div>
            </form></details>
        @endif
        @if($correctingId)<form wire:submit="correct" class="ops-panel ops-form"><h3 class="ops-full">Zeit korrigieren</h3><x-operations.field label="Beginn" model="correction.starts_at" type="datetime-local" required /><x-operations.field label="Ende" model="correction.ends_at" type="datetime-local" required /><x-operations.field label="Pause (min)" model="correction.pause_minutes" type="number" min="0" required /><x-operations.field label="Korrekturgrund" model="correction.note" required minlength="5" /><div class="ops-full ops-actions"><x-ui.buttons.button-basic type="submit" mode="primary" wire:loading.attr="disabled">Korrektur speichern</x-ui.buttons.button-basic><x-ui.buttons.button-basic wire:click="cancelCorrection">Abbrechen</x-ui.buttons.button-basic></div></form>@endif
        <section>@forelse($times as $entry)<article class="ops-panel ops-stack" wire:key="my-time-{{ $entry->id }}"><header class="ops-toolbar"><div><p class="ops-kicker">{{ $entry->starts_at->format('d.m.Y') }} · Revision {{ $entry->revision }}</p><h3>{{ $entry->plan_snapshot['title'] }}</h3></div><x-operations.status :value="$entry->status" /></header><div class="ops-toolbar"><p>{{ $entry->starts_at->format('H:i') }} – {{ $entry->ends_at?->format('H:i') ?? 'Läuft' }} · {{ intdiv($entry->pause_seconds,60) }} min Pause</p><strong>{{ \App\Support\Operations\OperationsDateTime::duration($entry->netSeconds()) }}</strong></div>@if($entry->review_note)<p class="ops-errors">{{ $entry->review_note }}</p>@endif<div class="ops-actions">@if(in_array($entry->status,['completed','returned']))<x-ui.buttons.button-basic wire:click="editTime({{ $entry->id }})">Korrigieren</x-ui.buttons.button-basic>@endif @if($entry->status === 'completed')<x-ui.buttons.button-basic mode="primary" wire:click="clock({{ $entry->id }},{{ $entry->revision }},'submit')" wire:loading.attr="disabled">Zur Prüfung einreichen</x-ui.buttons.button-basic>@endif</div></article>@empty<div class="ops-panel ops-empty">Noch keine Zeitmeldungen.</div>@endforelse{{ $times->links() }}</section>
    @else
        <div class="ops-split"><section class="ops-stack"><header class="ops-toolbar"><h2>Meine Nachweise</h2></header><details class="ops-panel"><summary>Nachweis einreichen</summary><form wire:submit="upload" class="ops-form"><x-operations.field label="Nachweisart" model="qualification.qualification_type_id" type="select" required :wide="true"><option value="">Auswählen</option>@foreach($types as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</x-operations.field><x-operations.field label="Gültig ab" model="qualification.valid_from" type="date" required /><x-operations.field label="Gültig bis" model="qualification.valid_until" type="date" required /><x-operations.field label="Datei · PDF, JPG oder PNG · max. 10 MB" model="evidence" type="file" accept="application/pdf,image/jpeg,image/png" required :wide="true" /><div class="ops-full"><x-ui.buttons.button-basic mode="primary" type="submit" wire:loading.attr="disabled">Einreichen</x-ui.buttons.button-basic></div></form></details><div class="ops-panel">@forelse($qualifications as $record)<div class="ops-row"><div><h3>{{ $record->type->name }}</h3><p class="ops-muted">{{ $record->valid_from->format('d.m.Y') }} – {{ $record->valid_until->format('d.m.Y') }}</p>@if($record->review_note)<p>{{ $record->review_note }}</p>@endif@if($record->evidence_path)<a class="ops-link" href="{{ route('operations.evidence',$record->id) }}">Datei öffnen</a>@endif</div><x-operations.status :value="$record->status" /></div>@empty<p class="ops-empty">Keine Nachweise eingereicht.</p>@endforelse{{ $qualifications->links() }}</div></section>
        <section class="ops-stack"><h2>Meine Abwesenheiten</h2><details class="ops-panel"><summary>Abwesenheit beantragen</summary><form wire:submit="requestAbsence" class="ops-form"><x-operations.field label="Art" model="absence.kind" type="select"><option value="vacation">Urlaub</option><option value="unavailable">Nicht verfügbar</option><option value="other">Abwesenheit</option></x-operations.field><x-operations.field label="Zeitzone" model="absence.timezone" required /><x-operations.field label="Beginn" model="absence.starts_at" type="datetime-local" required /><x-operations.field label="Ende" model="absence.ends_at" type="datetime-local" required /><x-operations.field label="Notiz (optional)" model="absence.note" maxlength="1000" :wide="true" /><div class="ops-full"><x-ui.buttons.button-basic mode="primary" type="submit" wire:loading.attr="disabled">Antrag einreichen</x-ui.buttons.button-basic></div></form></details><div class="ops-panel">@forelse($absences as $record)<div class="ops-row"><div><h3>{{ ['vacation'=>'Urlaub','unavailable'=>'Nicht verfügbar','other'=>'Abwesenheit'][$record->kind] }}</h3><p class="ops-muted">{{ $record->starts_at->format('d.m.Y H:i') }} – {{ $record->ends_at->format('d.m.Y H:i') }}</p>@if($record->review_note)<p>{{ $record->review_note }}</p>@endif @if($record->status === 'pending')<x-ui.buttons.button-basic mode="link" wire:click="withdraw({{ $record->id }},{{ $record->revision }})">Zurückziehen</x-ui.buttons.button-basic>@endif</div><x-operations.status :value="$record->status" /></div>@empty<p class="ops-empty">Keine Abwesenheiten.</p>@endforelse{{ $absences->links() }}</div></section></div>
    @endif
</div>
