<section class="rt-ops ops-stack min-w-0" aria-label="Planungswerkzeuge">
    @php
        $tabs=['capacity'=>'Kapazität','bundles'=>'Qualifikationsbündel','fairness'=>'Verteilung','rotations'=>'Rotationen','teams'=>'Teams','chains'=>'Dienstketten','positions'=>'Stellenplanung','optimizer'=>'Planvorschlag'];
        $columns=match($tab){
            'bundles'=>[['label'=>'Bündel','key'=>'bundle'],['label'=>'Anforderungen','key'=>'requirements'],['label'=>'Status','key'=>'status'],['label'=>'Aktionen','key'=>'actions']],
            'teams'=>[['label'=>'Team','key'=>'name'],['label'=>'Mitglieder','key'=>'members'],['label'=>'Aktionen','key'=>'actions']],
            'rotations'=>[['label'=>'Rotation','key'=>'name'],['label'=>'Zyklus','key'=>'cycle'],['label'=>'Aktionen','key'=>'actions']],
            'chains'=>[['label'=>'Dienstkette','key'=>'chain'],['label'=>'Übergabe','key'=>'handover'],['label'=>'Ressourcen','key'=>'resources']],
            'fairness'=>[['label'=>'Mitarbeiter','key'=>'name'],['label'=>'Nächte','key'=>'nights'],['label'=>'Wochenenden','key'=>'weekends'],['label'=>'Gewählte Tätigkeiten','key'=>'unfavourable'],['label'=>'Planstunden','key'=>'planned_hours'],['label'=>'Wochensoll','key'=>'weekly_target']],
            'positions'=>[['label'=>'Stellenplan','key'=>'name'],['label'=>'Ziel-FTE','key'=>'target_fte'],['label'=>'Bekannte FTE','key'=>'known_fte'],['label'=>'Unbekannt','key'=>'unknown'],['label'=>'Fehlende FTE','key'=>'gap_fte'],['label'=>'Freigabe','key'=>'actions']],
            default=>[['label'=>'Dienst','key'=>'name'],['label'=>'Tätigkeit / Ort','key'=>'context'],['label'=>'Beginn','key'=>'period'],['label'=>'Bedarf','key'=>'required'],['label'=>'Reserviert','key'=>'reserved'],['label'=>'Bestätigt','key'=>'confirmed'],['label'=>'Geeignet frei','key'=>'eligible'],['label'=>'Unterdeckung','key'=>'missing'],['label'=>'Nachweisrisiko','key'=>'proof_risks']]
        };
    @endphp
    <header class="ops-toolbar">@if(!$embedded)<nav class="ops-actions" aria-label="Planungsbereiche">@foreach($tabs as $key=>$label)<x-ui.buttons.button-basic type="button" :mode="$tab===$key?'primary':'secondary'" wire:click="setTab('{{ $key }}')" :aria-current="$tab===$key?'page':'false'">{{ $label }}</x-ui.buttons.button-basic>@endforeach</nav>@endif
        @if(in_array($tab,['bundles','teams','rotations','chains','positions']))<x-ui.buttons.button-basic type="button" wire:click="edit('{{ ['bundles'=>'bundle','teams'=>'team','rotations'=>'rotation','chains'=>'chain','positions'=>'position'][$tab] }}')"><i class="far fa-plus" aria-hidden="true"></i>{{ ['bundles'=>'Bündel','teams'=>'Team','rotations'=>'Rotation','chains'=>'Dienstkette','positions'=>'Stellenplan'][$tab] }} anlegen</x-ui.buttons.button-basic>@endif
    </header>
    <x-operations.feedback />
    @if(in_array($tab,['capacity','fairness','positions','optimizer']))
        <div class="ops-form"><x-operations.field label="Von" model="from" type="date" /><x-operations.field label="Bis" model="until" type="date" />
            @if($tab==='capacity')<x-operations.field label="Tätigkeit" model="filters.role" /><x-operations.field label="Standort" model="filters.location" /><x-operations.field label="Pool" model="filters.pool_id" type="select"><option value="">Alle</option>@foreach($pools as $pool)<option value="{{ $pool->id }}">{{ $pool->name }}</option>@endforeach</x-operations.field>@endif
            @if(in_array($tab,['fairness','optimizer']))<x-operations.field label="Nachtfenster von" model="goals.night_start" type="time" /><x-operations.field label="Nachtfenster bis" model="goals.night_end" type="time" />@endif
            @if($tab==='fairness')<fieldset class="ops-full ops-actions"><legend class="text-sm font-semibold">Tätigkeiten vergleichen</legend>@foreach($shifts->pluck('role_name')->unique()->sort() as $role)<x-ui.forms.checkbox wire:model="unfavourableRoles" :value="$role" :label="$role" />@endforeach</fieldset>@endif
            <div class="ops-actions"><x-ui.buttons.button-basic type="button" wire:click="$refresh" wire:loading.attr="disabled">Aktualisieren</x-ui.buttons.button-basic></div>
        </div>
    @endif
    @if($tab==='optimizer')
        <div class="ops-form">@foreach(['wish_weight'=>'Wünsche','load_weight'=>'Planstunden','night_weight'=>'Nächte','weekend_weight'=>'Wochenenden'] as $key=>$label)<x-operations.field :label="'Gewicht: '.$label" :model="'goals.'.$key" type="number" min="0" max="100" />@endforeach<div class="ops-full ops-actions"><x-ui.buttons.button-basic type="button" wire:click="prepare" wire:loading.attr="disabled">Vorschlag berechnen</x-ui.buttons.button-basic>@if(isset($preview['fingerprint']))<x-ui.buttons.button-basic type="button" mode="primary" wire:click="applyPreview" wire:loading.attr="disabled">Als Planvariante speichern</x-ui.buttons.button-basic><span class="ops-muted tabular-nums">{{ $preview['open'] }} offene Plätze</span>@endif</div></div>
        @if(isset($preview['rows']))<x-tables.table :columns="[['label'=>'Dienst','key'=>'name'],['label'=>'Beginn','key'=>'period'],['label'=>'Vorher','key'=>'before'],['label'=>'Vorschlag','key'=>'after'],['label'=>'Offen','key'=>'open'],['label'=>'Begründung','key'=>'proposals']]" :items="collect($preview['rows'])->map(fn($r)=>(object)$r)" row-view="components.tables.rows.operations.planning-enhancement" />@endif
        <x-tables.table :columns="[['label'=>'Variante','key'=>'name'],['label'=>'Status','key'=>'status'],['label'=>'Aktionen','key'=>'variant_actions']]" :items="$variants" row-view="components.tables.rows.operations.planning-enhancement" empty="Keine Planvarianten." />
    @else
        <x-tables.table :columns="$columns" :items="$items" row-view="components.tables.rows.operations.planning-enhancement" empty="Keine Einträge im Zeitraum." />
    @endif
    @if($tab==='capacity')
        <h2 class="text-base font-semibold">Auftragsbedarf</h2><x-tables.table :columns="[['label'=>'Auftrag / Tätigkeit','key'=>'name'],['label'=>'Bedarf','key'=>'required'],['label'=>'Geplant','key'=>'planned'],['label'=>'Reserviert','key'=>'reserved'],['label'=>'Bestätigt','key'=>'confirmed'],['label'=>'Offen','key'=>'missing']]" :items="collect($matrix['demands'])->map(fn($r)=>(object)$r)" row-view="components.tables.rows.operations.planning-enhancement" empty="Keine offenen Bedarfe." />
        <h2 class="text-base font-semibold">Wochenkapazität</h2><x-tables.table :columns="[['label'=>'Woche','key'=>'name'],['label'=>'Modelle','key'=>'known'],['label'=>'Unbekannt','key'=>'unknown'],['label'=>'Modellstunden','key'=>'target_hours'],['label'=>'Dienstplanung','key'=>'planned_hours'],['label'=>'Schulung','key'=>'training_hours'],['label'=>'Modellrest','key'=>'remaining_hours']]" :items="collect($matrix['weeks'])->map(fn($r)=>(object)$r)" row-view="components.tables.rows.operations.planning-enhancement" />
        @if($matrix['limited'])<p class="ops-muted">Erste 500 Dienste. Zeitraum oder Filter eingrenzen.</p>@endif
    @endif
    <div class="hidden"><x-operations.modal wire:model="formOpen" :title="match($modal){'bundle'=>'Bündelversion','attach'=>'Anforderung zuordnen','team'=>'Team','bulk'=>'Team einteilen','rotation'=>'Rotation','rotation-preview'=>'Rotationsvorschau','chain'=>'Dienstkette','position'=>'Stellenplan',default=>'Planvariante prüfen'}" max-width="4xl">
        @if(in_array($modal,['bulk','rotation-preview','variant','bundle-coverage']))
            @if($modal==='bulk')<fieldset class="ops-stack"><legend class="text-sm font-semibold">Dienste</legend>@foreach($shifts as $shift)<x-ui.forms.checkbox wire:model="form.shift_ids" :value="$shift->id" :label="$shift->starts_at->setTimezone($shift->timezone)->format('d.m. H:i').' · '.$shift->title" />@endforeach</fieldset>
            @elseif($modal==='rotation-preview')<div class="ops-form"><x-operations.field label="Von" model="form.from" type="date" /><x-operations.field label="Bis" model="form.until" type="date" /></div>@elseif($modal==='bundle-coverage')<x-operations.field label="Stichtag" model="form.date" type="date" />@endif
            @if(isset($preview['rows']))<x-tables.table :columns="$modal==='bundle-coverage'?[['label'=>'Mitarbeiter','key'=>'name'],['label'=>'Pflichtnachweise','key'=>'mandatory_coverage'],['label'=>'Entwicklungsziele','key'=>'development_coverage'],['label'=>'Stand','key'=>'requirement_state'],['label'=>'Schulungsbedarf','key'=>'training_need']]:[['label'=>'Dienst','key'=>'preview_title'],['label'=>'Mitarbeiter / Plätze','key'=>'preview_people'],['label'=>'Prüfung','key'=>'preview_issues']]" :items="collect($preview['rows'])->values()->map(fn($r,$i)=>(object)($r+['id'=>$i+1]))" row-view="components.tables.rows.operations.planning-enhancement" />@endif
            <div class="ops-actions">@if($modal!=='variant')<x-ui.buttons.button-basic type="button" wire:click="prepare" wire:loading.attr="disabled">Vorschau</x-ui.buttons.button-basic>@if(isset($preview['fingerprint']) && ($preview['valid'] ?? false) && ($preview['can_create'] ?? true))<x-ui.buttons.button-basic type="button" mode="primary" wire:click="applyPreview" wire:loading.attr="disabled">{{ $modal==='bulk'?'Alle anfragen':'Planvariante erstellen' }}</x-ui.buttons.button-basic>@endif
                @elseif($preview['valid'] ?? false)<x-ui.buttons.button-basic type="button" mode="primary" wire:click="approveVariant" wire:loading.attr="disabled">Variante freigeben</x-ui.buttons.button-basic>@endif<x-ui.buttons.button-basic type="button" wire:click="$set('formOpen',false)">Schließen</x-ui.buttons.button-basic></div>
        @else
            <form wire:submit="save" class="ops-form">
                @if($modal==='bundle')<x-operations.field label="Name" model="form.name" required /><x-operations.field label="Tätigkeit" model="form.role_name" required /><fieldset class="ops-full grid gap-2 sm:grid-cols-2"><legend class="text-sm font-semibold">Zwingende Nachweise</legend>@foreach($types as $type)<x-ui.forms.checkbox wire:model="form.qualification_ids" :value="$type->id" :label="$type->name" />@endforeach</fieldset><fieldset class="ops-full grid gap-2 sm:grid-cols-2"><legend class="text-sm font-semibold">Entwicklungsziele</legend>@foreach($types as $type)<x-ui.forms.checkbox wire:model="form.development_ids" :value="$type->id" :label="$type->name" />@endforeach</fieldset>
                @elseif($modal==='attach')<div class="space-y-1.5"><x-ui.forms.label for="bundle-shift" value="Dienstentwurf" /><x-ui.forms.select id="bundle-shift" wire:model.live="form.shift_id"><option value="">Auswählen</option>@foreach($shifts->filter(fn($s)=>$s->status->value==='draft' && $s->published_revision===0) as $shift)<option value="{{ $shift->id }}">{{ $shift->starts_at->setTimezone($shift->timezone)->format('d.m. H:i') }} · {{ $shift->title }}</option>@endforeach</x-ui.forms.select></div><x-operations.field label="Dienst / Abschnitt" model="form.scope" required />
                @elseif($modal==='team')<x-operations.field label="Teamname" model="form.name" required /><x-ui.forms.checkbox wire:model="form.is_active" label="Aktiv" /><fieldset class="ops-full grid gap-2 sm:grid-cols-2"><legend class="text-sm font-semibold">Mitglieder</legend>@foreach($people as $person)<x-ui.forms.checkbox wire:model="form.user_ids" :value="$person->id" :label="$person->name" />@endforeach</fieldset>
                @elseif($modal==='rotation')<x-operations.field label="Name" model="form.name" required /><x-operations.field label="Startanker" model="form.anchor" type="date" required /><x-operations.field label="Zyklus in Tagen" model="form.cycle_days" type="number" min="1" max="84" /><x-operations.field label="Zeitzone" model="form.timezone" required />
                    @foreach($form['slots'] ?? [] as $i=>$slot)<fieldset class="ops-full ops-form" wire:key="rotation-slot-{{ $i }}"><legend class="text-sm font-semibold">Zyklusdienst {{ $i+1 }}</legend><x-operations.field label="Zyklustag (ab 0)" :model="'form.slots.'.$i.'.day'" type="number" min="0" max="83" /><x-operations.field label="Versatz in Tagen" :model="'form.slots.'.$i.'.offset'" type="number" min="-365" max="365" /><x-operations.field label="Vorlagendienst" :model="'form.slots.'.$i.'.shift_id'" type="select"><option value="">Auswählen</option>@foreach($shifts as $shift)<option value="{{ $shift->id }}">{{ $shift->title }} · {{ $shift->role_name }}</option>@endforeach</x-operations.field><x-operations.field label="Team" :model="'form.slots.'.$i.'.team_id'" type="select"><option value="">Offen planen</option>@foreach($teams as $team)<option value="{{ $team->id }}">{{ $team->name }}</option>@endforeach</x-operations.field>@if(count($form['slots'])>1)<x-ui.buttons.button-basic type="button" wire:click="removeSlot({{ $i }})">Entfernen</x-ui.buttons.button-basic>@endif</fieldset>@endforeach
                    <div class="ops-full ops-actions"><x-ui.buttons.button-basic type="button" wire:click="addSlot">Zyklusdienst hinzufügen</x-ui.buttons.button-basic><x-ui.buttons.button-basic type="button" wire:click="addException">Ausnahme hinzufügen</x-ui.buttons.button-basic></div>
                    @foreach($form['exceptions'] ?? [] as $i=>$exception)<fieldset class="ops-full ops-form" wire:key="rotation-exception-{{ $i }}"><legend class="text-sm font-semibold">Ausnahme {{ $i+1 }}</legend><x-operations.field label="Datum" :model="'form.exceptions.'.$i.'.date'" type="date" /><x-operations.field label="Mitarbeiter" :model="'form.exceptions.'.$i.'.user_id'" type="select"><option value="">Gesamter Zyklusdienst entfällt</option>@foreach($people as $person)<option value="{{ $person->id }}">{{ $person->name }}</option>@endforeach</x-operations.field><x-ui.buttons.button-basic type="button" wire:click="removeException({{ $i }})">Entfernen</x-ui.buttons.button-basic></fieldset>@endforeach
                @elseif($modal==='chain')@foreach(['predecessor_id'=>'Vorhergehender Dienst','successor_id'=>'Folgedienst'] as $key=>$label)<div class="space-y-1.5"><x-ui.forms.label :for="'chain-'.$key" :value="$label" /><x-ui.forms.select :id="'chain-'.$key" wire:model.live="form.{{ $key }}"><option value="">Auswählen</option>@foreach($shifts as $shift)<option value="{{ $shift->id }}">{{ $shift->starts_at->setTimezone($shift->timezone)->format('d.m. H:i') }} · {{ $shift->title }}</option>@endforeach</x-ui.forms.select></div>@endforeach<x-operations.field label="Übergabeort" model="form.handover_location" required /><x-operations.field label="Transferpuffer (min)" model="form.transfer_minutes" type="number" min="0" max="10080" /><x-operations.field label="Zugreferenz" model="form.train_code" /><x-operations.field label="Fahrzeugreferenz" model="form.vehicle_code" /><x-ui.forms.checkbox wire:model="form.same_employee" label="Gleicher Mitarbeiter in beiden Diensten" />
                @elseif($modal==='position')<x-operations.field label="Name" model="form.name" required /><x-operations.field label="Tätigkeit" model="form.role_name" required /><x-operations.field label="Standort" model="form.location_name" /><x-operations.field label="Von" model="form.from" type="date" /><x-operations.field label="Bis" model="form.until" type="date" /><x-operations.field label="Ziel-FTE" model="form.target_fte" type="number" step="0.001" min="0" max="999" /><x-operations.field label="Vollzeit-Referenz (min/Woche)" model="form.full_time_week_minutes" type="number" min="1" max="10080" /><fieldset class="ops-full grid gap-2 sm:grid-cols-2"><legend class="text-sm font-semibold">Benötigte Nachweise</legend>@foreach($types as $type)<x-ui.forms.checkbox wire:model="form.qualification_ids" :value="$type->id" :label="$type->name" />@endforeach</fieldset>@endif
                <div class="ops-full ops-actions"><x-ui.buttons.button-basic type="submit" mode="primary" wire:loading.attr="disabled">{{ $modal==='bundle' && $recordId?'Neue Version erstellen':'Speichern' }}</x-ui.buttons.button-basic><x-ui.buttons.button-basic type="button" wire:click="$set('formOpen',false)">Abbrechen</x-ui.buttons.button-basic></div>
            </form>
        @endif
    </x-operations.modal></div>
</section>
