<div class="rt-ops ops-stack">
    <x-operations.feedback />
    @if(!$ready)
        <p class="text-sm text-rt-muted">Personalmodelle sind noch nicht verfügbar.</p>
    @else
        @if(!$embedded)<header class="ops-toolbar">
            @if(!$personal)<div><x-ui.forms.label for="workforce-person" value="Mitarbeiter"/><x-ui.forms.select id="workforce-person" wire:model.live="userId"><option value="0">Auswählen</option>@foreach($employees as $person)<option value="{{ $person->id }}">{{ $person->name }}</option>@endforeach</x-ui.forms.select></div>@endif
            @php($viewOptions = $personal ? [['value'=>'account','label'=>'Konten','icon'=>'fa-wallet'],['value'=>'absences','label'=>'Abwesenheiten','icon'=>'fa-calendar-days'],['value'=>'tasks','label'=>'Aufgaben','icon'=>'fa-list-check'],['value'=>'training','label'=>'Schulungen','icon'=>'fa-graduation-cap']] : ($processOnly ? [['value'=>'tasks','label'=>'Aufgaben','icon'=>'fa-list-check'],['value'=>'training','label'=>'Schulungen','icon'=>'fa-graduation-cap']] : [['value'=>'account','label'=>'Konten','icon'=>'fa-wallet'],['value'=>'models','label'=>'Arbeitsmodelle','icon'=>'fa-clock'],['value'=>'policies','label'=>'Urlaubsrichtlinien','icon'=>'fa-umbrella-beach'],['value'=>'rules','label'=>'Regeln','icon'=>'fa-shield'],['value'=>'checks','label'=>'Prüfungen','icon'=>'fa-clipboard-check'],['value'=>'absences','label'=>'Abwesenheiten','icon'=>'fa-calendar-days']]))
            @if(!$personal && !$processOnly && auth()->user()->isAdmin())@php($viewOptions[] = ['value'=>'responsibilities','label'=>'Zuständigkeiten','icon'=>'fa-users-gear'])@endif
            <x-ui.buttons.multi-toggle id="workforce-account-view" label="Personalansicht" :value="$tab" action="showTab" :options="$viewOptions" />
        </header>@endif
        @if($employee)
            @if($tab === 'account')<div class="ops-form"><x-operations.field label="Von" model="from" type="date"/><x-operations.field label="Bis" model="until" type="date"/><div class="ops-full"><x-ui.buttons.button-basic type="button" wire:click="$refresh">Anzeigen</x-ui.buttons.button-basic></div></div>@endif
            @if($tab === 'account')
                @if($accountKind !== 'vacation')<div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
                    @foreach(['target_minutes'=>'Soll','actual_minutes'=>'Freigegebenes Ist','credited_minutes'=>'Kontogutschrift','absence_credit_minutes'=>'Urlaubsgutschrift','balance_minutes'=>'Saldo'] as $key=>$label)
                        <section class="ops-panel"><p class="text-xs text-rt-muted">{{ $label }}</p><p class="text-xl font-semibold tabular-nums">{{ $summary[$key] === null ? 'Prüfung erforderlich' : ($summary[$key] < 0 ? '−' : '').\App\Support\Operations\OperationsDateTime::duration(abs($summary[$key]) * 60) }}</p></section>
                    @endforeach
                </div>@endif
                @php($vacation = $summary['vacation'])
                @if($accountKind !== 'time')<div class="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">@foreach(['available'=>'Verfügbar','reserved'=>'Reserviert','approved'=>'Genehmigt','used'=>'Verbraucht','expired'=>'Abgelaufen','credited'=>'Anspruch'] as $key=>$label)<section class="ops-panel"><p class="text-xs text-rt-muted">{{ $label }}</p><p class="font-semibold tabular-nums">{{ !$vacation['configured'] ? '—' : ($vacation[$key] === null ? 'Prüfung erforderlich' : ($vacation['unit'] === 'days' ? number_format($vacation[$key] / 100, 2, ',', '.').' Tage' : $vacation[$key].' min')) }}</p></section>@endforeach</div>
                @if(!$vacation['configured'])<p class="text-sm text-rt-muted">Urlaubsrichtlinie fehlt.</p>@endif
                @if($summary['missing_absence_allocations'] !== [])<p class="text-sm text-amber-700 dark:text-amber-300">Urlaubsübernahme prüfen.</p>@endif @endif
            @endif
            <div class="ops-actions">
                @if($canConfigure && $tab === 'account')@if($accountKind !== 'time')<x-ui.buttons.button-basic type="button" wire:click="openForm('credit')">Anspruch buchen</x-ui.buttons.button-basic>@endif @if($accountKind !== 'vacation')<x-ui.buttons.button-basic type="button" wire:click="openForm('adjustment')">Zeitkorrektur</x-ui.buttons.button-basic>@endif @endif
                @if($canConfigure && $tab === 'models')<x-ui.buttons.button-basic type="button" wire:click="openForm('model')">Arbeitsmodell</x-ui.buttons.button-basic>@endif
                @if($canConfigure && $tab === 'policies')<x-ui.buttons.button-basic type="button" wire:click="openForm('policy')">Urlaubsrichtlinie</x-ui.buttons.button-basic>@endif
                @if($canConfigure && $tab === 'rules')<x-ui.buttons.button-basic type="button" wire:click="openForm('rule')">Regeln zuordnen</x-ui.buttons.button-basic>@endif
                @if(!$personal && $tab === 'responsibilities' && auth()->user()->isAdmin())<x-ui.buttons.button-basic type="button" wire:click="openForm('responsibility')">Zuständigkeit</x-ui.buttons.button-basic>@endif
                @if($canProcesses && $tab === 'tasks')<x-ui.buttons.button-basic type="button" wire:click="openForm('task')">Aufgabe</x-ui.buttons.button-basic>@endif
                @if($canTraining && $tab === 'training')<x-ui.buttons.button-basic type="button" wire:click="openForm('training')">Schulung</x-ui.buttons.button-basic><x-ui.buttons.button-basic type="button" wire:click="openForm('enroll')">Teilnehmer zuordnen</x-ui.buttons.button-basic>@endif
                @if($personal && $tab === 'absences')<x-ui.buttons.button-basic type="button" wire:click="openForm('vacation')">Urlaub beantragen</x-ui.buttons.button-basic><x-ui.buttons.button-basic type="button" wire:click="openForm('sick')">Krankmelden</x-ui.buttons.button-basic>@endif
            </div>
            <x-tables.table :columns="[['label'=>'Eintrag','key'=>'label'],['label'=>'Zeitraum / Wert','key'=>'value'],['label'=>'Status','key'=>'status'],['label'=>'Aktionen','key'=>'actions']]" :items="$records" row-view="components.tables.rows.operations.workforce-account" empty="Keine Einträge." />
            @if($records instanceof \Illuminate\Contracts\Pagination\Paginator){{ $records->links() }}@endif
        @else<p class="text-sm text-rt-muted">Keine Mitarbeiter vorhanden.</p>@endif
    @endif
    <x-operations.modal wire:model="formOpen" :title="$formKind === 'plan_review' ? 'Dienst neu beurteilen' : 'Personal'">
        <form wire:submit="save" class="ops-form">
            @if($formKind === 'model')
                <x-operations.field label="Bezeichnung" model="form.name" required :wide="true"/><x-operations.field label="Gültig ab" model="form.starts_on" type="date" required/><x-operations.field label="Gültig bis" model="form.ends_on" type="date"/><x-operations.field label="Zeitzone" model="form.timezone" required/><x-operations.field label="Wochensoll (min)" model="form.weekly_target_minutes" type="number" min="0" required/><x-operations.field label="Wochenlimit (min)" model="form.maximum_weekly_minutes" type="number" min="0"/>
                @foreach([1=>'Montag',2=>'Dienstag',3=>'Mittwoch',4=>'Donnerstag',5=>'Freitag',6=>'Samstag',7=>'Sonntag'] as $day=>$label)<x-operations.field :label="$label.' (min)'" :model="'form.daily_minutes.'.$day" type="number" min="0" required/><div class="grid grid-cols-2 gap-2"><x-operations.field :label="$label.' ab'" :model="'form.window_start.'.$day" type="time"/><x-operations.field :label="$label.' bis (HH:MM)'" :model="'form.window_end.'.$day" placeholder="24:00"/></div>@endforeach
                @foreach([1=>'Montag',2=>'Dienstag',3=>'Mittwoch',4=>'Donnerstag',5=>'Freitag',6=>'Samstag',7=>'Sonntag'] as $day=>$label)<div class="ops-full grid grid-cols-2 gap-2"><x-operations.field :label="$label.' zweites Fenster ab'" :model="'form.window_start_2.'.$day" type="time"/><x-operations.field :label="$label.' zweites Fenster bis'" :model="'form.window_end_2.'.$day" placeholder="24:00"/></div>@endforeach
                <h3 class="ops-full text-sm font-medium">Zeitgutschrift</h3>@foreach(['work'=>'Arbeit','preparation'=>'Vorbereitung','driving'=>'Fahrt','shunting'=>'Rangieren','travel'=>'Anreise','waiting'=>'Wartezeit','on_call'=>'Bereitschaft','break'=>'Pause','internal'=>'Interne Arbeit','training'=>'Schulung'] as $kind=>$label)<x-operations.field :label="$label.' (%)'" :model="'form.valuation_percent.'.$kind" type="number" min="0" max="100" step="0.01" placeholder="Nicht konfiguriert"/>@endforeach
            @elseif($formKind === 'policy')
                <x-operations.field label="Bezeichnung" model="form.name" required :wide="true"/><x-operations.field label="Gültig ab" model="form.starts_on" type="date" required/><x-operations.field label="Gültig bis" model="form.ends_on" type="date"/><x-operations.field label="Einheit" model="form.unit" type="select" required><option value="">Auswählen</option><option value="days">Tage</option><option value="minutes">Minuten</option></x-operations.field><x-operations.field label="Feiertagsregion" model="form.holiday_region"/><x-operations.field label="Kalenderstand" model="form.calendar_version" required/><x-operations.field label="Arbeitsfreie Daten (JJJJ-MM-TT)" model="form.non_working_dates_text" type="textarea" :wide="true"/>
            @elseif($formKind === 'credit')
                <x-operations.field label="Buchungsdatum" model="form.effective_on" type="date" required/><x-operations.field label="Ablauf" model="form.expires_on" type="date"/><x-operations.field label="Anspruchsjahr" model="form.entitlement_year" type="number" required/><x-operations.field label="Menge in Richtlinieneinheit" model="form.amount" type="number" min="0.01" step="0.01" required/><x-operations.field label="Art" model="form.kind" type="select"><option value="grant">Anspruch</option><option value="carry">Übertrag</option><option value="manual">Manuelle Gutschrift</option></x-operations.field><x-operations.field label="Begründung / Quelle" model="form.note" required :wide="true"/>
            @elseif($formKind === 'adjustment')
                <x-operations.field label="Buchungsdatum" model="form.effective_on" type="date" required/><x-operations.field label="Korrektur (min)" model="form.quantity" type="number" required/><x-operations.field label="Begründung" model="form.note" required :wide="true"/>
            @elseif($formKind === 'rule')
                <x-operations.field label="Regelprofil" model="form.operations_rule_profile_id" type="select" required><option value="">Auswählen</option>@foreach($rules as $rule)<option value="{{ $rule->id }}">{{ $rule->name }}</option>@endforeach</x-operations.field><x-operations.field label="Gültig ab" model="form.starts_on" type="date" required/><x-operations.field label="Gültig bis" model="form.ends_on" type="date"/>
            @elseif($formKind === 'task')
                <x-operations.field label="Aufgabe" model="form.title" required :wide="true"/><x-operations.field label="Prozess" model="form.type" type="select"><option value="general">Personal</option><option value="onboarding">Eintritt</option><option value="offboarding">Austritt</option></x-operations.field><x-operations.field label="Verantwortlich" model="form.assigned_to" type="select" required><option value="">Auswählen</option>@foreach($assignees as $person)<option value="{{ $person->id }}">{{ $person->name }}</option>@endforeach</x-operations.field><x-operations.field label="Fällig am" model="form.due_on" type="date"/><x-operations.field label="Notiz" model="form.note" type="textarea" :wide="true"/>
            @elseif($formKind === 'training')
                <x-operations.field label="Schulung" model="form.title" required :wide="true"/><x-operations.field label="Nachweisart" model="form.qualification_type_id" type="select"><option value="">Keine Zuordnung</option>@foreach($types as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</x-operations.field><x-operations.field label="Beginn" model="form.starts_at" type="datetime-local" required/><x-operations.field label="Ende" model="form.ends_at" type="datetime-local" required/><x-operations.field label="Zeitzone" model="form.timezone" required/><x-operations.field label="Plätze" model="form.capacity" type="number" min="1" required/>
            @elseif($formKind === 'enroll')
                <div class="ops-full"><x-ui.forms.label for="workforce-training" value="Schulung"/><x-ui.forms.select id="workforce-training" wire:model.live="form.personnel_training_id" wire:change="selectTraining" required><option value="">Auswählen</option>@foreach($trainings as $training)<option value="{{ $training->id }}">{{ $training->title }} · {{ $training->starts_at->format('d.m.Y H:i') }}</option>@endforeach</x-ui.forms.select></div>
            @elseif($formKind === 'responsibility')
                <x-operations.field label="Verantwortlich" model="form.responsible_user_id" type="select" required><option value="">Auswählen</option>@foreach($assignees as $person)<option value="{{ $person->id }}">{{ $person->name }}</option>@endforeach</x-operations.field><x-operations.field label="Gültig ab" model="form.starts_on" type="date" required/><x-operations.field label="Gültig bis" model="form.ends_on" type="date"/>
                <fieldset class="ops-full grid gap-2 sm:grid-cols-2"><legend class="text-sm font-medium">Zuständigkeiten</legend>@foreach(['employees.master-data.view'=>'Personal anzeigen','employees.master-data.edit'=>'Personal bearbeiten','operations.rules.manage'=>'Regeln verwalten','operations.absences.review'=>'Abwesenheiten prüfen','operations.qualifications.manage'=>'Nachweise / Schulung','operations.time.review'=>'Arbeitszeit prüfen','operations.time.export'=>'Arbeitszeit exportieren'] as $ability=>$label)<label class="flex items-center gap-2"><x-ui.forms.checkbox wire:model="form.abilities" :value="$ability"/><span class="text-sm">{{ $label }}</span></label>@endforeach</fieldset>
            @elseif($formKind === 'vacation')
                <x-operations.field label="Erster Tag" model="form.starts_on" type="date" required/><x-operations.field label="Letzter Tag" model="form.ends_on" type="date" required/><div><x-ui.forms.label for="workforce-vacation-portion" value="Anteil"/><x-ui.forms.select id="workforce-vacation-portion" wire:model.live="form.vacation_fraction"><option value="1">Ganze Tage</option><option value="0.5">Halber Tag</option>@if($vacationWindowAvailable)<option value="window">Zeitfenster</option>@endif</x-ui.forms.select></div>@if(($form['vacation_fraction'] ?? '1') !== '1')<x-operations.field label="Von (Uhrzeit)" model="form.starts_time" type="time" required/><x-operations.field label="Bis (Uhrzeit)" model="form.ends_time" type="time" required/>@endif<x-operations.field label="Notiz" model="form.note" :wide="true"/>
            @elseif(in_array($formKind, ['sick','sickness_correction']))
                <x-operations.field label="Beginn" model="form.starts_at" type="datetime-local" required/><x-operations.field label="Voraussichtliches Ende" model="form.ends_at" type="datetime-local" required/><x-operations.field label="Zeitzone" model="form.timezone" required/>@if($formKind === 'sickness_correction')<x-operations.field label="Korrekturgrund" model="form.note" required :wide="true"/>@endif
            @else
                @if(in_array($formKind,['end_model','end_policy']))<x-operations.field label="Gültig bis" model="form.ends_on" type="date" required/>@endif
                @if($formKind === 'reduce_credit')<x-operations.field :label="$correctionUnit === 'days' ? 'Korrektur (Tage)' : 'Korrektur (min)'" model="form.quantity" type="number" :min="$correctionUnit === 'days' ? '0.01' : '1'" :step="$correctionUnit === 'days' ? '0.01' : '1'" required/>@endif
                @if($formKind === 'participation')<x-operations.field label="Aktion" model="form.action" type="select"><option value="attend">Teilnahme bestätigen</option><option value="cancel">Teilnahme stornieren</option></x-operations.field>@endif
                <x-operations.field label="Begründung" model="form.note" required :wide="true"/>
            @endif
            <div class="ops-full ops-actions"><x-ui.buttons.button-basic type="submit" mode="primary" wire:loading.attr="disabled">Speichern</x-ui.buttons.button-basic><x-ui.buttons.button-basic type="button" wire:click="$set('formOpen',false)">Abbrechen</x-ui.buttons.button-basic></div>
        </form>
    </x-operations.modal>
</div>
