                @if($formKind === 'survey')
                    <x-operations.field label="Frage" model="form.question" type="textarea" required :wide="true"/><x-operations.field label="Bis" model="form.until" type="date" required/><x-operations.field label="Mindestens Antworten" model="form.threshold" type="number" min="5" max="100" required/><fieldset class="ops-full grid gap-2 sm:grid-cols-2"><legend class="text-sm font-medium">Freiwillige Einladung</legend>@foreach($employees as $person)<label class="flex items-center gap-2"><x-ui.forms.checkbox wire:model="form.user_ids" :value="$person->id"/><span class="text-sm">{{ $person->name }}</span></label>@endforeach</fieldset>
                @elseif($formKind === 'survey_response')
                    <p class="ops-full text-sm font-medium">{{ $display['question'] ?? '' }}</p><x-operations.field label="Aktion" model="form.action" type="select"><option value="submit">Antworten</option><option value="decline">Nicht teilnehmen</option><option value="withdraw">Antwort zurückziehen</option></x-operations.field><x-operations.field label="Bewertung (1–5)" model="form.score" type="number" min="1" max="5"/>
                @elseif($formKind === 'sickness')
                    <x-operations.field label="Krankmeldung" model="form.absence_request_id" type="select" required><option value="">Auswählen</option>@foreach($sicknesses as $absence)<option value="{{ $absence->id }}">{{ $absence->starts_at->setTimezone($absence->timezone)->format('d.m.Y') }} – {{ $absence->ends_at->setTimezone($absence->timezone)->subSecond()->format('d.m.Y') }}</option>@endforeach</x-operations.field><x-operations.field label="Nachweisfrist" model="form.due_on" type="date" required/>
                @elseif($formKind === 'sickness_update')
                    <x-operations.field label="Status" model="form.action" type="select"><option value="submitted">Nachweis gemeldet</option>@if(!$personal)<option value="follow_up">Rückfrage</option><option value="covered">Vollständig abgedeckt</option><option value="uncovered">Abdeckung fehlt</option>@endif</x-operations.field>@if(!$personal)<x-operations.field label="Abgedeckt von" model="form.covered_from" type="date"/><x-operations.field label="Abgedeckt bis" model="form.covered_until" type="date"/>@endif<x-operations.field label="Rückmeldung" model="form.note" type="textarea" required :wide="true"/>
                    @foreach($display['history'] ?? [] as $event)<p class="ops-full text-sm text-rt-muted">{{ $event['note'] }}</p>@endforeach
                @endif

