                @if($formKind === 'approval_policy')
                    <x-operations.field label="Team" model="form.team_id" type="select"><option value="">Alle Teams</option>@foreach($teams as $team)<option value="{{ $team->id }}">{{ $team->name }}</option>@endforeach</x-operations.field>
                    <x-operations.field label="Abwesenheitsart" model="form.kind" type="select"><option value="vacation">Urlaub</option><option value="unavailable">Nicht verfügbar</option><option value="other">Andere</option></x-operations.field><x-operations.field label="Ab Tagen" model="form.minimum_days" type="number" min="1" max="366" required/><x-operations.field label="Bis Tagen" model="form.maximum_days" type="number" min="1" max="366" required/>
                    @foreach($form['stages'] ?? [] as $i=>$stage)<fieldset class="ops-full ops-form border-t border-rt-border pt-4" wire:key="absence-chain-stage-{{ $i }}"><legend class="text-sm font-semibold">Stufe {{ $i+1 }}</legend><x-operations.field label="Freigabe durch" :model="'form.stages.'.$i.'.reviewer_id'" type="select" required><option value="">Auswählen</option>@foreach($assignees as $person)<option value="{{ $person->id }}">{{ $person->name }}</option>@endforeach</x-operations.field><x-operations.field label="Vertretung" :model="'form.stages.'.$i.'.delegate_id'" type="select"><option value="">Keine</option>@foreach($assignees as $person)<option value="{{ $person->id }}">{{ $person->name }}</option>@endforeach</x-operations.field><x-operations.field label="Frist (Stunden)" :model="'form.stages.'.$i.'.hours'" type="number" min="1" max="720" required/></fieldset>@endforeach
                    <div class="ops-full ops-actions"><x-ui.buttons.button-basic type="button" wire:click="addStep">Stufe hinzufügen</x-ui.buttons.button-basic><x-ui.buttons.button-basic type="button" wire:click="removeLastStep">Letzte entfernen</x-ui.buttons.button-basic></div>
                @elseif($formKind === 'approval_retire')
                    <x-operations.field label="Begründung" model="form.note" type="textarea" required :wide="true"/>
                @elseif($formKind === 'absence_review')
                    <x-operations.field label="Entscheidung" model="form.action" type="select"><option value="approve">Stufe freigeben</option><option value="reject">Ablehnen</option></x-operations.field><x-operations.field label="Begründung" model="form.note" type="textarea" :wide="true"/>
                @elseif($formKind === 'calendar')
                    <x-operations.field label="Region" model="form.region" required/><x-operations.field label="Jahr" model="form.year" type="number" min="2000" max="2200" required/><x-operations.field label="Arbeitsfreie Daten (JJJJ-MM-TT)" model="form.dates_text" type="textarea" :wide="true"/><x-operations.field label="Prüfquelle" model="form.source" required :wide="true"/>
                @elseif($formKind === 'calendar_apply')
                    @if(($display['affected_absences'] ?? []) !== [])<p class="ops-full text-sm text-amber-700 dark:text-amber-300">{{ count($display['affected_absences']) }} bestehende Urlaubsanträge bleiben unverändert.</p>@endif
                    <p class="ops-full text-sm">{{ $display['region'] ?? '' }} · {{ $display['year'] ?? '' }}</p><div class="ops-full flex flex-wrap gap-2">@foreach($display['dates'] ?? [] as $date)<span class="text-sm tabular-nums">{{ $date }}</span>@endforeach</div><x-operations.field label="Urlaubseinheit" model="form.unit" type="select"><option value="days">Tage</option><option value="minutes">Minuten</option></x-operations.field>
                @endif

