@php $needsException = ! empty($assignmentReview['temporal_issues']); @endphp
<section class="rt-staffing-section rt-staffing-editor" data-assignment-review wire:key="staffing-review-{{ $selectedShift->id }}-{{ $selectedCandidate->id }}" aria-label="Zuweisung prüfen" tabindex="-1" x-data x-init="$nextTick(() => { $el.focus({ preventScroll: true }); $el.scrollIntoView({ block: 'start', behavior: 'auto' }); })">
    <div class="rt-staffing-heading"><div><h3>{{ $needsException ? 'Zeitkonflikt prüfen' : 'Zuweisung vorbereiten' }}</h3><p>{{ $needsException ? 'Bewusste Ausnahme · nur mit dokumentierter Prüfung' : 'Noch nicht gespeichert' }}</p></div><button type="button" class="rt-ops-panel__icon-button" wire:click="cancelCandidateSelection" aria-label="Auswahl verwerfen"><i class="far fa-xmark" aria-hidden="true"></i></button></div>
    <x-user.person-anchor-preview :user="$selectedCandidate" :show-presence="false" :show-email="false" :size="9" />
    <p class="rt-staffing-note"><strong>{{ $selectedShift->title }}</strong><br>{{ $shiftWindow }}@if($shiftLocation) · {{ $shiftLocation }}@endif</p>
    <div class="rt-staffing-filters">
        <div><x-ui.forms.label for="staffing-assignment-status" value="Zuweisungsstatus" /><x-ui.forms.select id="staffing-assignment-status" wire:model="assignmentStatus">@foreach($assignmentStatusOptions as $option)<option value="{{ $option['value'] }}">{{ $option['label'] }}</option>@endforeach</x-ui.forms.select>@error('assignmentStatus')<p class="rt-staffing-alert">{{ $message }}</p>@enderror</div>
        <div><x-ui.forms.label for="staffing-assignment-note" value="Hinweis (optional)" /><x-ui.forms.input id="staffing-assignment-note" wire:model="assignmentNote" maxlength="2000" />@error('assignmentNote')<p class="rt-staffing-alert">{{ $message }}</p>@enderror</div>
    </div>
    @if($needsException)
        <div class="rt-staffing-warning" role="note"><h4><i class="far fa-triangle-exclamation" aria-hidden="true"></i> Vor der Einteilung klären</h4><ul>@foreach($assignmentReview['temporal_issues'] as $issue)<li>{{ $issue['message'] }}</li>@endforeach</ul></div>
        @if(!empty($assignmentReview['rules']['profile_id']))
            <div class="rt-staffing-rules"><h4>Hinterlegtes Regelprofil: {{ $assignmentReview['rules']['profile_name'] }}</h4><dl><div><dt>Mindestruhezeit</dt><dd>{{ number_format($assignmentReview['rules']['minimum_rest_minutes'] / 60, 1, ',', '.') }} h</dd></div><div><dt>Maximale Schicht</dt><dd>{{ number_format($assignmentReview['rules']['maximum_shift_minutes'] / 60, 1, ',', '.') }} h</dd></div><div><dt>Planpause</dt><dd>{{ $assignmentReview['rules']['minimum_break_minutes'] }} min ab mehr als {{ number_format($assignmentReview['rules']['break_after_minutes'] / 60, 1, ',', '.') }} h</dd></div></dl><p class="rt-staffing-note">Dies sind die gepflegten Planungswerte, keine Bestätigung ihrer rechtlichen Vollständigkeit.</p></div>
        @endif
        @if(!empty($assignmentReview['conflicts']))
            <div class="rt-staffing-conflicts"><h4>Betroffene Dienste</h4>@foreach($assignmentReview['conflicts'] as $conflict)
                <div><strong>{{ $conflict['title'] ?? 'Dienst' }}</strong>@if(!empty($conflict['starts_at']) && !empty($conflict['ends_at']))<p>{{ \Carbon\CarbonImmutable::parse($conflict['starts_at'])->setTimezone($displayTimezone)->format('d.m. H:i') }} – {{ \Carbon\CarbonImmutable::parse($conflict['ends_at'])->setTimezone($displayTimezone)->format('d.m. H:i') }}@if(!empty($conflict['location_name'])) · {{ $conflict['location_name'] }}@endif</p>@endif<p>@if(($conflict['type'] ?? '') === 'overlap'){{ $conflict['overlap_minutes'] }} Minuten Überschneidung @else{{ $conflict['gap_minutes'] }} Minuten Abstand · {{ $conflict['required_rest_minutes'] }} Minuten Ruhezeit vorgesehen @endif · {{ ($conflict['same_location'] ?? false) ? 'gleiche Ortsbezeichnung (Durchführbarkeit trotzdem prüfen)' : 'Ortswechsel oder Ortslage ungeklärt' }}</p></div>
            @endforeach</div>
        @endif
        <details class="rt-staffing-more" open><summary>Pausen, Ruhezeit und Folgen</summary>
            <p><strong>Geplante Pause in dieser Schicht: {{ $selectedShift->planned_break_minutes }} Minuten.</strong> Eine Planpause allein weist weder ihre tatsächliche Lage noch eine Unterbrechung aller parallelen Tätigkeiten nach.</p>
            <p>Gesetzlicher Ausgangspunkt: bei mehr als 6 bis 9 Stunden Arbeit mindestens 30 Minuten Pause, über 9 Stunden mindestens 45 Minuten; Teilpausen mindestens 15 Minuten, höchstens 6 Stunden ohne Pause. Grundsätzlich 11 Stunden ununterbrochene Ruhezeit. Im Regelfall 8 Stunden werktäglich; bis 10 Stunden nur mit dem erforderlichen Ausgleich.</p>
            <p><strong>Lösung prüfen:</strong> Zeiten entzerren, Vertretung einplanen oder einen tatsächlich gemeinsam ausführbaren Einsatz am selben Ort abgrenzen. Pausen ohne parallele Arbeit und notwendige Ruhe-/Ausgleichszeiten konkret planen. Für Abweichungen muss eine anwendbare rechtliche oder tarifliche Grundlage bestehen.</p>
            <p><strong>Die Ausnahme ist nur eine Planungsfreigabe.</strong> Warnungen bleiben bestehen; Arbeitszeiten, Pausen und Abrechnung werden nicht automatisch geändert. Es darf weiterhin nur eine Zeiterfassung gleichzeitig laufen: parallele Aufgaben sind keine doppelte Arbeitszeit. Die tatsächliche Zeitzuordnung und gemeinsame Pausen müssen gesondert geklärt werden. Die Freigabe mit Person, Zeitpunkt, Gründen und Prüfstand wird protokolliert. Sie ersetzt keine rechtliche Zulässigkeitsprüfung.</p>
            <p><a href="https://www.gesetze-im-internet.de/arbzg/__3.html" target="_blank" rel="noopener noreferrer">ArbZG § 3</a> · <a href="https://www.gesetze-im-internet.de/arbzg/__4.html" target="_blank" rel="noopener noreferrer">§ 4</a> · <a href="https://www.gesetze-im-internet.de/arbzg/__5.html" target="_blank" rel="noopener noreferrer">§ 5</a> · <a href="https://www.gesetze-im-internet.de/arbzg/__7.html" target="_blank" rel="noopener noreferrer">§ 7</a></p>
        </details>
        <div><x-ui.forms.label for="staffing-exception-reason" value="Begründung, konkrete Lösung und Ausgleich" /><textarea id="staffing-exception-reason" wire:model="exceptionReason" rows="3" minlength="20" maxlength="2000" class="rt-ui-input rt-staffing-textarea" placeholder="Welche Aufgaben sind gemeinsam durchführbar? Wie sind Pausen, Ruhezeit und Verantwortung abgesichert?"></textarea>@error('exceptionReason')<p class="rt-staffing-alert" role="alert">{{ $message }}</p>@enderror</div>
        <x-ui.forms.checkbox id="staffing-exception-acknowledgment" wire:model="exceptionAcknowledged" label="Ich habe Konflikte, Durchführbarkeit und die geltenden Pausen-/Ruhezeitpflichten geprüft und dokumentiere die Ausnahme in eigener Zuständigkeit." />
        @error('exceptionAcknowledged')<p class="rt-staffing-alert" role="alert">{{ $message }}</p>@enderror
        @if(!$exceptionPrepared)
            <x-ui.buttons.button-basic type="button" wire:click="prepareAssignmentException" wire:loading.attr="disabled">Ausnahme prüfen und fortfahren <i class="far fa-arrow-right" aria-hidden="true"></i></x-ui.buttons.button-basic>
        @else
            <div class="rt-staffing-warning" data-exception-final-confirmation><h4>Ausnahme verbindlich bestätigen</h4><p>Die Einteilung von {{ $selectedCandidate->name }} wird trotz der angezeigten Zeitkonflikte gespeichert. Geben Sie zur bewussten Bestätigung <strong>FREIGEBEN</strong> ein.</p><x-ui.forms.label for="staffing-exception-confirm" value="Bestätigung" /><x-ui.forms.input id="staffing-exception-confirm" wire:model="exceptionConfirmation" autocomplete="off" placeholder="FREIGEBEN" />@error('exceptionConfirmation')<p class="rt-staffing-alert" role="alert">{{ $message }}</p>@enderror<x-ui.buttons.button-basic type="button" mode="primary" wire:click="confirmAssignmentException" wire:loading.attr="disabled">Mit dokumentierter Ausnahme zuweisen</x-ui.buttons.button-basic></div>
        @endif
    @else
        <p class="rt-staffing-note">Beim Speichern werden Qualifikation, Verfügbarkeit, Region und freie Plätze erneut geprüft.</p>
        <div class="rt-staffing-actions"><x-ui.buttons.button-basic type="button" wire:click="cancelCandidateSelection">Abbrechen</x-ui.buttons.button-basic><x-ui.buttons.button-basic type="button" mode="primary" wire:click="assignEmployee" wire:loading.attr="disabled"><i class="far fa-user-plus" aria-hidden="true"></i> Verbindlich zuweisen</x-ui.buttons.button-basic></div>
    @endif
</section>
