<!doctype html>
<html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>RailTime · Leistungsübersicht</title>
<style>
@page{size:A4 landscape;margin:16mm}*{box-sizing:border-box}body{font:12px/1.5 Arial,sans-serif;color:#17242c;margin:32px auto;padding:0 24px;max-width:1200px}header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #17242c;margin-bottom:24px;padding-bottom:16px}h1{font-size:24px;line-height:1.2;margin:8px 0}p{margin:4px 0;color:#52616c}button{background:#17242c;color:#fff;border:0;border-radius:6px;padding:12px 18px;font:inherit;cursor:pointer}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:9px 8px;border-bottom:1px solid #dce2e6;vertical-align:top;overflow-wrap:anywhere}th{font-size:10px;letter-spacing:.05em;text-transform:uppercase;color:#52616c}thead{display:table-header-group}tr{break-inside:avoid}.window{white-space:nowrap}footer{margin-top:24px;font-size:10px;color:#52616c}@media print{body{margin:0;padding:0;max-width:none}.print-actions{display:none}header{break-after:avoid}a{color:inherit;text-decoration:none}}@media(max-width:600px){body{padding:0 12px;margin:20px auto}header{display:block}.print-actions{margin-top:16px}.table-scroll{overflow-x:auto}table{min-width:700px}}
</style></head><body>
<header><div><strong>RAILTIME</strong><h1>Leistungsübersicht</h1><p>{{ $customer['company_name'] }} · {{ $customer['customer_number'] }}</p><p>Stand {{ now(config('operations.display_timezone','Europe/Berlin'))->format('d.m.Y H:i') }}</p></div><div class="print-actions"><button type="button" onclick="window.print()">Drucken / als PDF speichern</button></div></header>
<div class="table-scroll"><table><thead><tr><th>Auftrag</th><th>Leistung</th><th>Status</th><th>Beginn</th><th>Ende</th><th>Zeitzone</th></tr></thead><tbody>
@forelse($rows as $row)<tr><td>{{ $row['number'] ?? '' }}</td><td>{{ $row['title'] }}</td><td>{{ \App\Support\Operations\OperationsNavigation::status($row['status']) }}</td><td class="window">{{ filled($row['starts_at'] ?? null) ? \Carbon\CarbonImmutable::parse($row['starts_at'])->setTimezone($row['timezone'] ?? 'Europe/Berlin')->format('d.m.Y H:i') : '—' }}</td><td class="window">{{ filled($row['ends_at'] ?? null) ? \Carbon\CarbonImmutable::parse($row['ends_at'])->setTimezone($row['timezone'] ?? 'Europe/Berlin')->format('d.m.Y H:i') : '—' }}</td><td>{{ $row['timezone'] ?? '' }}</td></tr>@empty<tr><td colspan="6">Keine freigegebenen Leistungen.</td></tr>@endforelse
</tbody></table></div><footer>RailTime · {{ count($rows) }} freigegebene Leistungen</footer>
</body></html>
